#requires -Version 5.1
[CmdletBinding()]
param([Parameter(Mandatory)][string]$ConfigurationPath,[Parameter(Mandatory)][string]$OutputPath,[Parameter(Mandatory)][string]$EvidenceRoot,[Parameter(Mandatory)][string]$ReleaseVersion,[Parameter(Mandatory)][ValidatePattern('^[0-9a-fA-F]{40}$')][string]$GoldenBaselineCommit,[switch]$SkipLiveEvidenceChecks)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$repositoryRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
. (Join-Path $repositoryRoot 'tools\validation\common\OperationalValidation.Common.ps1');. (Join-Path $repositoryRoot 'tools\validation\common\OperationalValidation.Reporting.ps1');. (Join-Path $PSScriptRoot 'ProductionReadiness.Evidence.ps1');. (Join-Path $PSScriptRoot 'ProductionReadiness.Checks.ps1')
$started=[datetime]::UtcNow
try{
 try{$configuration=Get-OperationalConfiguration $ConfigurationPath $repositoryRoot;if($ReleaseVersion -notmatch '^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$' -or $configuration.Deployment.ReleaseVersion -ne $ReleaseVersion){throw 'ReleaseVersion must match validated deployment configuration.'};$root=Test-ProductionEvidenceRoot $EvidenceRoot $repositoryRoot;$hash=Get-OperationalConfigurationHash $ConfigurationPath}catch{[Console]::Error.WriteLine((Protect-OperationalText $_.Exception.Message));Write-Output 'PRODUCTION READINESS: NOT READY FOR PRODUCTION';exit 3}
 $operations=@{GetRepositoryFacts={param($baseline)Get-ProductionRepositoryFacts $repositoryRoot $baseline};ReadEvidence={param($relative)Read-ProductionEvidence $root $relative $ReleaseVersion $configuration.Deployment.GitCommit $hash};GetLiveConfigurationApproval={Test-Path -LiteralPath (Join-Path $root 'Configuration\LiveConfigurationApproval.json')};GetMonitoringRiskAcceptance={Test-Path -LiteralPath (Join-Path $root 'Risks\MonitoringBackendAcceptance.json')};GetRequiredApprovals={Test-Path -LiteralPath (Join-Path $root 'Approvals\ProductionSignOff.json')}}
 $assessment=Invoke-ProductionReadinessChecks $configuration $root $ReleaseVersion $GoldenBaselineCommit $hash $SkipLiveEvidenceChecks.IsPresent $operations;$report=New-OperationalReport $configuration $hash 'repository-and-evidence' $ReleaseVersion $started $assessment.Gates 'Production Readiness Report' 'ProductionReadiness';$report|Add-Member FinalDecision $assessment.Decision;$report|Add-Member GoldenBaselineCommit $GoldenBaselineCommit;$report|Add-Member EvidenceRoot '<external-evidence-root>';$paths=Write-OperationalReports $report $OutputPath
 $console=@{READY_FOR_CONTROLLED_PRODUCTION_DEPLOYMENT='READY FOR CONTROLLED PRODUCTION DEPLOYMENT';READY_WITH_WARNINGS='READY WITH WARNINGS';NOT_READY_FOR_PRODUCTION='NOT READY FOR PRODUCTION';INSUFFICIENT_LIVE_EVIDENCE='INSUFFICIENT LIVE EVIDENCE'};Write-Output "JSON: $($paths.Json)";Write-Output "Markdown: $($paths.Markdown)";Write-Output "Log: $($paths.Log)";Write-Output "PRODUCTION READINESS: $($console[$assessment.Decision])";exit (Get-ProductionDecisionExitCode $assessment.Decision)
}catch{[Console]::Error.WriteLine((Protect-OperationalText $_.Exception.Message));Write-Output 'PRODUCTION READINESS: NOT READY FOR PRODUCTION';exit 4}
