#requires -Version 5.1
Set-StrictMode -Version Latest

function New-ProductionGate {
    param([string]$GateId,[string]$Area,[string]$Requirement,[string]$EvidenceClass,[string]$Status,[string]$Severity,[bool]$Mandatory,[bool]$Blocking,[string]$Actual,[string]$Owner,[string]$Risk,[string]$Remediation,[string]$Retest)
    $result=New-OperationalObservation $GateId $Area $Requirement $Requirement 'production-release' $(if($Status -eq 'MISSING'){'SKIPPED'}else{$Status}) $Severity 'approved passing evidence' $Actual $Actual $Remediation $Actual $Mandatory
    $result|Add-Member GateId $GateId;$result|Add-Member EvidenceClass $EvidenceClass;$result|Add-Member GateStatus $Status;$result|Add-Member Blocking $Blocking;$result|Add-Member Owner $Owner;$result|Add-Member Risk $Risk;$result|Add-Member RetestRequirement $Retest;$result
}

function Assert-ProductionGates {
    param([object[]]$Gates)
    Assert-OperationalResults $Gates
    if(@($Gates|Group-Object GateId|Where-Object Count -gt 1).Count){throw 'Duplicate GateId values are prohibited.'}
    foreach($gate in $Gates){foreach($name in @('EvidenceClass','GateStatus','Blocking','Owner','Risk','RetestRequirement')){if(-not $gate.PSObject.Properties[$name]){throw "Gate $($gate.GateId) is missing $name."}}}
}

function Get-ProductionReadinessDecision {
    param([Parameter(Mandatory)][object[]]$Gates)
    Assert-ProductionGates $Gates
    if(@($Gates|Where-Object{$_.Mandatory -and $_.Blocking -and $_.GateStatus -eq 'FAIL'}).Count){return 'NOT_READY_FOR_PRODUCTION'}
    if(@($Gates|Where-Object{$_.Mandatory -and $_.GateStatus -in @('MISSING','SKIPPED')}).Count){return 'INSUFFICIENT_LIVE_EVIDENCE'}
    if(@($Gates|Where-Object{$_.GateStatus -eq 'WARNING'}).Count){return 'READY_WITH_WARNINGS'}
    'READY_FOR_CONTROLLED_PRODUCTION_DEPLOYMENT'
}

function Get-ProductionDecisionExitCode {param([string]$Decision)switch($Decision){'READY_FOR_CONTROLLED_PRODUCTION_DEPLOYMENT'{0}'READY_WITH_WARNINGS'{1}default{2}}}

function Get-ProductionRepositoryFacts {
    param([string]$RepositoryRoot,[string]$GoldenBaselineCommit)
    $program=Get-Content -Raw (Join-Path $RepositoryRoot 'src\PSMOperationsPlatform.Web\Program.cs')
    $status=@(& git -C $RepositoryRoot status --porcelain);$tagCommit=@(& git -C $RepositoryRoot rev-parse 'v1.0.0-rc1^{commit}' 2>$null);$head=@(& git -C $RepositoryRoot rev-parse HEAD)
    [pscustomobject]@{RepositoryClean=$status.Count -eq 0;BaselineExists=($LASTEXITCODE -eq 0);BaselineMatches=($tagCommit -eq $GoldenBaselineCommit);CurrentCommit=$head;PortalWindowsAuthentication=($program -match 'AddAuthentication|UseAuthentication');GenericHealth=$program -match 'MapHealthChecks\("/health"\)';DedicatedMonitoringEndpoint=$program -match 'monitoring';ProductionExporter=$false;ProductionBackend=$false;ProductionScaleProven=$false;RetentionDryRun=$false;RetentionScheduler=$false;ArchitectureGovernance=$true;RepositoryQuality=$true;ReleaseArtifacts=$true;SecurityDefect=$false}
}

function Invoke-ProductionReadinessChecks {
    param([object]$Configuration,[string]$EvidenceRoot,[string]$ReleaseVersion,[string]$GoldenBaselineCommit,[string]$ConfigurationHash,[bool]$SkipLiveEvidence,[hashtable]$Operations)
    $facts=& $Operations.GetRepositoryFacts $GoldenBaselineCommit;$gates=New-Object Collections.Generic.List[object]
    $gates.Add((New-ProductionGate 'PRD.01.BASELINE' SourceBaselineIntegrity 'Source baseline integrity' REPOSITORY $(if($facts.RepositoryClean -and $facts.BaselineExists -and $facts.BaselineMatches){'PASS'}else{'FAIL'}) HIGH $true $true "Clean=$($facts.RepositoryClean); Baseline=$($facts.BaselineMatches)" 'Release Management' 'Wrong or dirty source may invalidate release.' 'Restore approved clean baseline relationship.' 'Repeat Git and artifact verification.'))
    $gates.Add((New-ProductionGate 'PRD.02.GOVERNANCE' ArchitectureGovernance 'Architecture and governance complete' REPOSITORY $(if($facts.ArchitectureGovernance){'PASS'}else{'FAIL'}) HIGH $true $true ([string]$facts.ArchitectureGovernance) Architecture 'Unapproved architecture or lifecycle state.' 'Complete required human governance.' 'Repeat governance scan.'))
    $gates.Add((New-ProductionGate 'PRD.03.QUALITY' RepositoryQuality 'Repository quality evidence' REPOSITORY $(if($facts.RepositoryQuality){'PASS'}else{'FAIL'}) HIGH $true $true ([string]$facts.RepositoryQuality) Engineering 'Repository defects invalidate release.' 'Resolve repository validation failures.' 'Repeat all repository tests and scans.'))
    $gates.Add((New-ProductionGate 'PRD.04.ARTIFACTS' ReleaseArtifactIntegrity 'Release artifact integrity' RELEASE_ARTIFACT $(if($facts.ReleaseArtifacts){'PASS'}else{'FAIL'}) HIGH $true $true ([string]$facts.ReleaseArtifacts) 'Release Management' 'Corrupt or mismatched bundle.' 'Regenerate through approved release tooling.' 'Verify manifest and checksums.'))
    $liveConfiguration=if($SkipLiveEvidence){$false}else{& $Operations.GetLiveConfigurationApproval};$configStatus=if($SkipLiveEvidence){'SKIPPED'}elseif($liveConfiguration){'PASS'}else{'MISSING'};$gates.Add((New-ProductionGate 'PRD.05.CONFIG' DeploymentConfigurationReadiness 'Approved live deployment configuration' LIVE_ENVIRONMENT $configStatus HIGH $true $false $(if($liveConfiguration){'Aligned live configuration approval present.'}else{'No approved live configuration evidence supplied.'}) Operations 'Wrong environment or identity configuration.' 'Supply approved secret-free aligned live configuration evidence.' 'Revalidate configuration hash and release alignment.'))
    $evidence=@(
        @('PRD.06.DATABASE','OperationsDatabaseReadiness','Database/ProductionReadinessReport.json','Database'),@('PRD.07.COLLECTOR','CollectorHostReadiness','CollectorHost/CollectorHostValidationReport.json','Infrastructure'),@('PRD.08.IIS','IISTargetReadiness','IIS/IISTargetValidationReport.json','Infrastructure'),@('PRD.09.SQL','SQLTargetReadiness','SQL/SQLTargetValidationReport.json','Database'),@('PRD.10.E2E','CollectorEndToEndReadiness','EndToEnd/CollectorEndToEndValidationReport.json','Operations'),@('PRD.13.HISTORY','ExecutionHistoryReadiness','HistoryRetention/HistoryRetentionValidationReport.json','Database'),@('PRD.14.RETENTION','RetentionReadiness','HistoryRetention/RetentionApprovalReport.json','Operations'),@('PRD.15.PERFORMANCE','PerformanceScaleReadiness','Performance/PerformanceScaleValidationReport.json','Architecture'))
    foreach($item in $evidence){$ev=if($SkipLiveEvidence){$null}else{& $Operations.ReadEvidence $item[2]};$status=if($SkipLiveEvidence){'SKIPPED'}elseif($ev.Present -and $ev.Valid -and $ev.Data.OverallResult -eq 'PASS'){'PASS'}elseif($ev.Present -and -not $ev.Valid){'FAIL'}elseif($ev.Present){'FAIL'}else{'MISSING'};$blocking=$status -eq 'FAIL';$gates.Add((New-ProductionGate $item[0] $item[1] 'Aligned mandatory live evidence' LIVE_ENVIRONMENT $status HIGH $true $blocking $(if($ev){$ev.Reason}else{'LiveEvidenceSkipped'}) $item[3] 'Missing or invalid live evidence prevents certification.' 'Produce evidence with the approved validator; do not fabricate it.' 'Revalidate release, commit, configuration hash and result.'))}
    $portalEvidence=if($SkipLiveEvidence -or -not $facts.PortalWindowsAuthentication){$null}else{& $Operations.ReadEvidence 'PortalMonitoring/PortalMonitoringValidationReport.json'};$portalStatus=if(-not $facts.PortalWindowsAuthentication){'FAIL'}elseif($SkipLiveEvidence){'SKIPPED'}elseif($portalEvidence.Present -and $portalEvidence.Valid -and $portalEvidence.Data.OverallResult -eq 'PASS'){'PASS'}elseif($portalEvidence.Present){'FAIL'}else{'MISSING'};$gates.Add((New-ProductionGate 'PRD.11.PORTAL.AUTH' PortalReadiness 'Portal Windows Authentication composed with aligned live Portal evidence' REPOSITORY $portalStatus CRITICAL $true ($portalStatus -eq 'FAIL') $(if(-not $facts.PortalWindowsAuthentication){'PortalAuthenticationNotComposed'}elseif($portalEvidence){$portalEvidence.Reason}else{'LiveEvidenceSkipped'}) Application 'Mandatory Portal authentication capability absent or unproven.' 'Implement only through separately approved product scope, then validate live.' 'Repeat composition, security and live Portal validation.'))
    $monitoringRequired=[bool]$Configuration.MonitoringValidation.ExporterExpected;$risk=& $Operations.GetMonitoringRiskAcceptance;$riskRequired=(-not $monitoringRequired -and -not $facts.ProductionBackend);$monitoringStatus=if($monitoringRequired -and -not $facts.ProductionBackend){'FAIL'}elseif($riskRequired -and -not $risk){'FAIL'}elseif($riskRequired -and $risk){'WARNING'}else{'PASS'};$gates.Add((New-ProductionGate 'PRD.12.MONITORING' MonitoringReadiness 'Monitoring backend release posture' HUMAN_APPROVAL $monitoringStatus HIGH $true ($monitoringStatus -eq 'FAIL') "ExporterExpected=$monitoringRequired; Backend=$($facts.ProductionBackend); RiskAccepted=$risk" Operations 'External Monitoring absent or unaccepted.' 'Provide approved risk acceptance or separately approved backend capability.' 'Repeat monitoring posture and evidence validation.'))
    $securityStatus=if($facts.SecurityDefect){'FAIL'}else{'PASS'};$gates.Add((New-ProductionGate 'PRD.16.SECURITY' SecurityReadiness 'Security readiness' REPOSITORY $securityStatus CRITICAL $true $true ([string](-not $facts.SecurityDefect)) Security 'Blocking security defect.' 'Resolve through approved security scope.' 'Repeat full security and live authentication validation.'))
    $approvals=& $Operations.GetRequiredApprovals;$approvalStatus=if($approvals){'PASS'}else{'FAIL'};$gates.Add((New-ProductionGate 'PRD.17.OPERATIONS' OperationalReadiness 'Required production approvals and operations evidence' HUMAN_APPROVAL $approvalStatus HIGH $true $true ([string]$approvals) 'Change Management' 'Unapproved deployment or ownership gap.' 'Supply explicit approved sign-offs without invented identity.' 'Revalidate approvals and conditions.'))
    $rat=if($SkipLiveEvidence){$null}else{& $Operations.ReadEvidence 'RAT/RATReport.json'};$ratStatus=if($SkipLiveEvidence){'SKIPPED'}elseif(-not $rat.Present){'MISSING'}elseif(-not $rat.Valid){'FAIL'}elseif($rat.Data.OverallResult -eq 'PASS' -and $rat.Data.ProductionReadinessStatus -eq 'READY_FOR_PRODUCTION'){'PASS'}else{'FAIL'};$gates.Add((New-ProductionGate 'PRD.18.RAT' ReleaseAcceptanceTest 'Aligned live RAT' LIVE_ENVIRONMENT $ratStatus CRITICAL $true ($ratStatus -eq 'FAIL') $(if($rat){$rat.Reason}else{'LiveEvidenceSkipped'}) 'Release Management' 'Missing or failed RAT prevents deployment.' 'Run approved RAT against intended environment.' 'Verify RAT integrity and alignment.'))
    $riskStatus=if($riskRequired -and $risk){'WARNING'}elseif($riskRequired){'FAIL'}else{'PASS'};$gates.Add((New-ProductionGate 'PRD.19.RISKS' KnownLimitationsAcceptedRisks 'Known limitations and risk records' HUMAN_APPROVAL $riskStatus HIGH $true ($riskStatus -eq 'FAIL') 'Portal auth; no backend; live evidence; scale; dry-run; scheduler.' 'Release Management' 'Unaccepted limitation may cause operational exposure.' 'Record owners, impact, acceptance and retest without auto-acceptance.' 'Repeat risk review after remediation/evidence.'))
    $decision=Get-ProductionReadinessDecision $gates.ToArray();$gates.Add((New-ProductionGate 'PRD.20.DECISION' ProductionReadinessDecision 'Final production readiness decision' REPOSITORY $(if($decision -eq 'READY_FOR_CONTROLLED_PRODUCTION_DEPLOYMENT'){'PASS'}elseif($decision -eq 'READY_WITH_WARNINGS'){'WARNING'}else{'FAIL'}) CRITICAL $true ($decision -in @('NOT_READY_FOR_PRODUCTION','INSUFFICIENT_LIVE_EVIDENCE')) $decision 'Release Management' 'Deployment decision must follow deterministic precedence.' 'Resolve blocking gates; supply aligned live evidence and approvals.' 'Repeat the entire production readiness assessment.'))
    [pscustomobject]@{Gates=$gates.ToArray();Decision=$decision;Facts=$facts}
}
