// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSMOperationsPlatform.Infrastructure.Persistence;

#nullable disable

namespace PSMOperationsPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OperationsDbContext))]
    [Migration("20260728210750_WP0083ExecutionPlanEngine")]
    partial class WP0083ExecutionPlanEngine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetailJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditLog_CorrelationId");

                    b.HasIndex("OccurredAt")
                        .IsDescending()
                        .HasDatabaseName("IX_AuditLog_OccurredAt");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_AuditLog_Entity");

                    b.ToTable("AuditLog", "audit", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_DetailJson_IsJson", "[DetailJson] IS NULL OR ISJSON([DetailJson]) = 1");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorDecisionCapabilityReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapabilityCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CapabilityCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CapabilityRuleVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("CapabilitySnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EvaluationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PrerequisiteStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ReadinessStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SourceInventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SourceInventoryVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("StrategyDecisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupportStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("StrategyDecisionId", "CapabilityCode")
                        .IsUnique();

                    b.ToTable("CollectorDecisionCapabilityReference", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_CollectorDecisionCapabilityReference_InventoryVersion", "[SourceInventoryVersion] > 0");

                            t.HasCheckConstraint("CK_CollectorDecisionCapabilityReference_RuleVersion", "[CapabilityRuleVersion] > 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorDecisionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BlockedCount")
                        .HasColumnType("int");

                    b.Property<int>("CapabilitySchemaVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("CapabilitySnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DecisionSchemaVersion")
                        .HasColumnType("int");

                    b.Property<int>("DisabledCount")
                        .HasColumnType("int");

                    b.Property<int>("EligibleCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("IndeterminateCount")
                        .HasColumnType("int");

                    b.Property<int>("InvalidCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NotApplicableCount")
                        .HasColumnType("int");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SourceInventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SourceInventoryVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("StrategyCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapabilitySnapshotId")
                        .HasDatabaseName("IX_CollectorDecisionPlan_CapabilitySnapshotId");

                    b.HasIndex("ManagedServerId")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectorDecisionPlan_ManagedServer");

                    b.HasIndex("ManagedServerId", "SourceInventoryRunId")
                        .HasDatabaseName("IX_CollectorDecisionPlan_SourceInventoryRunId");

                    b.ToTable("CollectorDecisionPlan", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_CollectorDecisionPlan_SourceInventoryVersion", "[SourceInventoryVersion] > 0");

                            t.HasCheckConstraint("CK_CollectorDecisionPlan_Versions", "[CapabilitySchemaVersion] > 0 AND [DecisionSchemaVersion] > 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorHeartbeat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollectorNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long?>("WorkingSetBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CollectorNodeId", "ObservedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_CollectorHeartbeat_Collector_ObservedAt");

                    b.ToTable("CollectorHeartbeat", "monitoring");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HostFqdn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InstanceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HostFqdn", "CollectorType", "InstanceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectorNode_Registration");

                    b.ToTable("CollectorNode", "collection");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CollectorNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_CollectorRun_Server_CreatedAt");

                    b.HasIndex("CollectorNodeId", "Status", "CreatedAt")
                        .HasDatabaseName("IX_CollectorRun_Collector_Status_CreatedAt");

                    b.ToTable("CollectorRun", "collection");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorStrategyDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DecisionStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EligibilityStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("int");

                    b.Property<string>("ExecutionReadinessStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresManualApproval")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StrategyCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StrategyVersion")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "StrategyCode")
                        .IsUnique();

                    b.ToTable("CollectorStrategyDecision", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_CollectorStrategyDecision_PriorityOrder", "[Priority] > 0 AND [ExecutionOrder] > 0");

                            t.HasCheckConstraint("CK_CollectorStrategyDecision_StrategyVersion", "[StrategyVersion] > 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CommandQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NotBefore")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TargetCollectorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId");

                    b.HasIndex("Status", "TargetCollectorType", "Priority", "NotBefore", "CreatedAt")
                        .HasDatabaseName("IX_CommandQueue_Status_Target_Priority");

                    b.ToTable("CommandQueueItem", "operations", t =>
                        {
                            t.HasCheckConstraint("CK_CommandQueueItem_PayloadJson_IsJson", "ISJSON([PayloadJson]) = 1");

                            t.HasCheckConstraint("CK_CommandQueueItem_Priority_NonNegative", "[Priority] >= 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.ExecutionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapabilitySchemaVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("CapabilitySnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("DecisionPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DecisionSchemaVersion")
                        .HasColumnType("int");

                    b.Property<int>("ExclusionCount")
                        .HasColumnType("int");

                    b.Property<int>("ExecutionPlanSchemaVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlanStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SourceInventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SourceInventoryVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("StepCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapabilitySnapshotId")
                        .HasDatabaseName("IX_ExecutionPlan_CapabilitySnapshotId");

                    b.HasIndex("ManagedServerId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExecutionPlan_ManagedServer");

                    b.HasIndex("ManagedServerId", "DecisionPlanId")
                        .HasDatabaseName("IX_ExecutionPlan_DecisionPlanId");

                    b.HasIndex("ManagedServerId", "SourceInventoryRunId")
                        .HasDatabaseName("IX_ExecutionPlan_SourceInventoryRunId");

                    b.ToTable("ExecutionPlan", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_ExecutionPlan_Counts", "[StepCount] >= 0 AND [ExclusionCount] >= 0");

                            t.HasCheckConstraint("CK_ExecutionPlan_SchemaVersions", "[CapabilitySchemaVersion] > 0 AND [DecisionSchemaVersion] > 0 AND [ExecutionPlanSchemaVersion] > 0");

                            t.HasCheckConstraint("CK_ExecutionPlan_SourceInventoryVersion", "[SourceInventoryVersion] > 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.ExecutionPlanExclusion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExecutionPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PlanningDisposition")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceDecisionStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StrategyCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StrategyVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionPlanId", "StrategyCode")
                        .IsUnique();

                    b.ToTable("ExecutionPlanExclusion", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_ExecutionPlanExclusion_StrategyVersion", "[StrategyVersion] > 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.ExecutionPlanExclusionCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapabilityCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CapabilityRuleVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("CapabilitySnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("ExclusionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceInventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SourceInventoryVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExclusionId", "CapabilityCode")
                        .IsUnique();

                    b.ToTable("ExecutionPlanExclusionCapability", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_ExecutionPlanExclusionCapability_InventoryVersion", "[SourceInventoryVersion] > 0");

                            t.HasCheckConstraint("CK_ExecutionPlanExclusionCapability_RuleVersion", "[CapabilityRuleVersion] > 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.ExecutionPlanStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BatchGroupCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("ExecutionPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InclusionReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<Guid>("LogicalStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParallelGroupCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresManualApproval")
                        .HasColumnType("bit");

                    b.Property<string>("RetryPolicyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RetryPolicyVersion")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceDecisionReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceDecisionStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StepSequence")
                        .HasColumnType("int");

                    b.Property<string>("StrategyCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StrategyVersion")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThrottlingClass")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TimeoutPolicyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TimeoutPolicyVersion")
                        .HasColumnType("int");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionPlanId", "LogicalStepId")
                        .IsUnique();

                    b.HasIndex("ExecutionPlanId", "StepSequence")
                        .IsUnique();

                    b.HasIndex("ExecutionPlanId", "StrategyCode")
                        .IsUnique();

                    b.ToTable("ExecutionPlanStep", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_ExecutionPlanStep_PolicyVersions", "[TimeoutPolicyVersion] > 0 AND [RetryPolicyVersion] > 0");

                            t.HasCheckConstraint("CK_ExecutionPlanStep_PositiveValues", "[StrategyVersion] > 0 AND [StepSequence] > 0 AND [Priority] > 0 AND [ExecutionOrder] > 0 AND [TimeoutSeconds] > 0");

                            t.HasCheckConstraint("CK_ExecutionPlanStep_ReadOnly", "[IsReadOnly] = 1");

                            t.HasCheckConstraint("CK_ExecutionPlanStep_TimeoutBound", "[TimeoutSeconds] <= 3600");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.InventorySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CollectorRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("char(64)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CollectorRunId", "SnapshotType", "SchemaVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_InventorySnapshot_RunContract");

                    b.HasIndex("ManagedServerId", "SnapshotType", "CapturedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_InventorySnapshot_Server_Type_CapturedAt");

                    b.ToTable("InventorySnapshot", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_InventorySnapshot_PayloadJson_IsJson", "ISJSON([PayloadJson]) = 1");

                            t.HasCheckConstraint("CK_InventorySnapshot_SchemaVersion_Positive", "[SchemaVersion] > 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.ManagedServer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConsecutiveConnectivityFailures")
                        .HasColumnType("int");

                    b.Property<int>("ConsecutiveInventoryFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Environment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fqdn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("InventoryVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastConnectivityAttemptAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LastConnectivityFailureCategory")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastConnectivityState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("LastConnectivitySuccessAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("LastInventoryAttemptAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("LastInventoryFailureCategory")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("LastInventorySuccessAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("LastSuccessfulTransport")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NextConnectivityAttemptAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("NextInventoryAttemptAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("WinRmHttpPort")
                        .HasColumnType("int");

                    b.Property<int>("WinRmHttpsPort")
                        .HasColumnType("int");

                    b.Property<int>("WinRmProbeTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<string>("WinRmTransportMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Fqdn")
                        .IsUnique()
                        .HasDatabaseName("UX_ManagedServer_Fqdn");

                    b.HasIndex("IsEnabled", "NextConnectivityAttemptAt")
                        .HasDatabaseName("IX_ManagedServer_Eligibility");

                    b.HasIndex("IsEnabled", "NextInventoryAttemptAt")
                        .HasDatabaseName("IX_ManagedServer_InventoryEligibility");

                    b.ToTable("ManagedServer", "configuration", t =>
                        {
                            t.HasCheckConstraint("CK_ManagedServer_ConnectivityFailures_NonNegative", "[ConsecutiveConnectivityFailures] >= 0");

                            t.HasCheckConstraint("CK_ManagedServer_InventoryFailures_NonNegative", "[ConsecutiveInventoryFailures] >= 0");

                            t.HasCheckConstraint("CK_ManagedServer_InventoryVersion_NonNegative", "[InventoryVersion] >= 0");

                            t.HasCheckConstraint("CK_ManagedServer_LastConnectivityFailureCategory", "[LastConnectivityFailureCategory] IS NULL OR [LastConnectivityFailureCategory] IN ('DnsFailure', 'ConnectionRefused', 'Timeout', 'TlsFailure', 'AuthenticationFailure', 'AuthorizationFailure', 'WinRmUnavailable', 'ProtocolFailure', 'Unexpected')");

                            t.HasCheckConstraint("CK_ManagedServer_LastConnectivityState", "[LastConnectivityState] IN ('Unknown', 'Reachable', 'Unreachable')");

                            t.HasCheckConstraint("CK_ManagedServer_LastInventoryFailureCategory", "[LastInventoryFailureCategory] IS NULL OR [LastInventoryFailureCategory] IN ('CollectionFailure', 'ParsingFailure', 'ValidationFailure', 'PersistenceFailure', 'Timeout', 'Unexpected')");

                            t.HasCheckConstraint("CK_ManagedServer_LastSuccessfulTransport", "[LastSuccessfulTransport] IS NULL OR [LastSuccessfulTransport] IN ('Https', 'Http')");

                            t.HasCheckConstraint("CK_ManagedServer_WinRmHttpPort_Range", "[WinRmHttpPort] >= 1 AND [WinRmHttpPort] <= 65535");

                            t.HasCheckConstraint("CK_ManagedServer_WinRmHttpsPort_Range", "[WinRmHttpsPort] >= 1 AND [WinRmHttpsPort] <= 65535");

                            t.HasCheckConstraint("CK_ManagedServer_WinRmProbeTimeout_Positive", "[WinRmProbeTimeoutSeconds] > 0");

                            t.HasCheckConstraint("CK_ManagedServer_WinRmTransportMode", "[WinRmTransportMode] IN ('Auto', 'HttpsOnly', 'HttpOnly')");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsBiosInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ManagedServerId");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SmbiosBiosVersion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SmbiosMajorVersion")
                        .HasColumnType("int");

                    b.Property<int?>("SmbiosMinorVersion")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Id", "InventoryRunId")
                        .HasDatabaseName("IX_WindowsBiosInventory_ManagedServer_InventoryRun");

                    b.ToTable("WindowsBiosInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsCapabilityEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapabilityCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ReadinessStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("RuleVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SupportStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "CapabilityCode")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsCapabilityEntry_Snapshot_CapabilityCode");

                    b.ToTable("WindowsCapabilityEntry", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_WindowsCapabilityEntry_RuleVersion", "[RuleVersion] > 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsCapabilityProvenance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapabilityEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FactCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FactKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("InventoryVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityEntryId", "FactCategory", "FactKey")
                        .IsUnique();

                    b.ToTable("WindowsCapabilityProvenance", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_WindowsCapabilityProvenance_InventoryVersion", "[InventoryVersion] > 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsCapabilitySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapabilitySchemaVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("EvaluationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SourceInventoryVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsCapabilitySnapshot_ManagedServer");

                    b.HasIndex("ManagedServerId", "InventoryRunId", "SourceInventoryVersion")
                        .HasDatabaseName("IX_WindowsCapabilitySnapshot_SourceInventory");

                    b.ToTable("WindowsCapabilitySnapshot", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_WindowsCapabilitySnapshot_SchemaVersion", "[CapabilitySchemaVersion] > 0");

                            t.HasCheckConstraint("CK_WindowsCapabilitySnapshot_SourceInventoryVersion", "[SourceInventoryVersion] > 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsComputerInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ManagedServerId");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ComputerName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DomainName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DomainRole")
                        .HasColumnType("int");

                    b.Property<string>("Fqdn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsVirtualMachine")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Model")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SystemType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id", "InventoryRunId")
                        .HasDatabaseName("IX_WindowsComputerInventory_ManagedServer_InventoryRun");

                    b.ToTable("WindowsComputerInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsDiskInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DiskKey")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int?>("DiskNumber")
                        .HasColumnType("int");

                    b.Property<string>("FriendlyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PartitionStyle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId", "DiskKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsDiskInventory_ManagedServer_DiskKey");

                    b.HasIndex("ManagedServerId", "InventoryRunId")
                        .HasDatabaseName("IX_WindowsDiskInventory_ManagedServer_InventoryRun");

                    b.ToTable("WindowsDiskInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsDotNetPlatformInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DotNetKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Release")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId", "DotNetKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsDotNetPlatformInventory_ManagedServer_DotNetKey");

                    b.HasIndex("ManagedServerId", "InventoryRunId")
                        .HasDatabaseName("IX_WindowsDotNetPlatformInventory_ManagedServer_InventoryRun");

                    b.ToTable("WindowsDotNetPlatformInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsFeatureInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("FeatureType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Parent")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RestartRequired")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId", "FeatureKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsFeatureInventory_ManagedServer_FeatureKey");

                    b.HasIndex("ManagedServerId", "InventoryRunId")
                        .HasDatabaseName("IX_WindowsFeatureInventory_ManagedServer_InventoryRun");

                    b.ToTable("WindowsFeatureInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsIisPlatformInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("IisKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Installed")
                        .HasColumnType("bit");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId", "IisKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsIisPlatformInventory_ManagedServer_IisKey");

                    b.HasIndex("ManagedServerId", "InventoryRunId")
                        .HasDatabaseName("IX_WindowsIisPlatformInventory_ManagedServer_InventoryRun");

                    b.ToTable("WindowsIisPlatformInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsIpv4AddressInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdapterKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DefaultGateway")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool?>("DnsRegistrationEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ipv4Key")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool?>("IsDhcp")
                        .HasColumnType("bit");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NetworkAdapterInventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PrefixLength")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("NetworkAdapterInventoryId")
                        .HasDatabaseName("IX_WindowsIpv4AddressInventory_NetworkAdapterInventoryId");

                    b.HasIndex("ManagedServerId", "InventoryRunId")
                        .HasDatabaseName("IX_WindowsIpv4AddressInventory_ManagedServer_InventoryRun");

                    b.HasIndex("ManagedServerId", "Ipv4Key")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsIpv4AddressInventory_ManagedServer_Ipv4Key");

                    b.HasIndex("NetworkAdapterInventoryId", "ManagedServerId");

                    b.ToTable("WindowsIpv4AddressInventory", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_WindowsIpv4AddressInventory_PrefixLength_Range", "[PrefixLength] >= 0 AND [PrefixLength] <= 32");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsMemoryInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankLabel")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("CapacityBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("ConfiguredClockSpeedMHz")
                        .HasColumnType("int");

                    b.Property<string>("DeviceLocator")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("FormFactor")
                        .HasColumnType("int");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MemoryType")
                        .HasColumnType("int");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SpeedMHz")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId", "InventoryRunId")
                        .HasDatabaseName("IX_WindowsMemoryInventory_ManagedServer_InventoryRun");

                    b.HasIndex("ManagedServerId", "ModuleKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsMemoryInventory_ManagedServer_ModuleKey");

                    b.ToTable("WindowsMemoryInventory", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_WindowsMemoryInventory_CapacityBytes_Positive", "[CapacityBytes] > 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsNetworkAdapterInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdapterKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("FriendlyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InterfaceDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InterfaceGuid")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int?>("InterfaceIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("LinkSpeedBitsPerSecond")
                        .HasColumnType("bigint");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OperationalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("PhysicalAdapter")
                        .HasColumnType("bit");

                    b.Property<string>("PnpDeviceId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "ManagedServerId")
                        .HasName("AK_WindowsNetworkAdapterInventory_Id_ManagedServerId");

                    b.HasIndex("ManagedServerId", "AdapterKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsNetworkAdapterInventory_ManagedServer_AdapterKey");

                    b.HasIndex("ManagedServerId", "InventoryRunId")
                        .HasDatabaseName("IX_WindowsNetworkAdapterInventory_ManagedServer_InventoryRun");

                    b.ToTable("WindowsNetworkAdapterInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsOperatingSystemInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ManagedServerId");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BuildNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("CurrentTimeZoneMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Edition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("InstallDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("InstallationType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastBootTime")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Locale")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProductType")
                        .HasColumnType("int");

                    b.Property<string>("SystemDrive")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WindowsDirectory")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.HasKey("Id");

                    b.HasIndex("Id", "InventoryRunId")
                        .HasDatabaseName("IX_WindowsOperatingSystemInventory_ManagedServer_InventoryRun");

                    b.ToTable("WindowsOperatingSystemInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsPowerShellPlatformInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PowerShellKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId", "InventoryRunId")
                        .HasDatabaseName("IX_WindowsPowerShellPlatformInventory_ManagedServer_InventoryRun");

                    b.HasIndex("ManagedServerId", "PowerShellKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsPowerShellPlatformInventory_ManagedServer_PowerShellKey");

                    b.ToTable("WindowsPowerShellPlatformInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsProcessorInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AddressWidth")
                        .HasColumnType("int");

                    b.Property<int?>("Architecture")
                        .HasColumnType("int");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("CoreCount")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentClockSpeedMhz")
                        .HasColumnType("int");

                    b.Property<int?>("DataWidth")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LogicalProcessorCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaxClockSpeedMhz")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProcessorId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProcessorKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool?>("SecondLevelAddressTranslationExtensions")
                        .HasColumnType("bit");

                    b.Property<string>("SocketDesignation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("VirtualizationFirmwareEnabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("VmMonitorModeExtensions")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId", "InventoryRunId")
                        .HasDatabaseName("IX_WindowsProcessorInventory_ManagedServer_InventoryRun");

                    b.HasIndex("ManagedServerId", "ProcessorKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsProcessorInventory_ManagedServer_ProcessorKey");

                    b.ToTable("WindowsProcessorInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsRoleInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FeatureType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Parent")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleKey")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId", "InventoryRunId")
                        .HasDatabaseName("IX_WindowsRoleInventory_ManagedServer_InventoryRun");

                    b.HasIndex("ManagedServerId", "RoleKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsRoleInventory_ManagedServer_RoleKey");

                    b.ToTable("WindowsRoleInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsVolumeInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DriveLetter")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FileSystem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("FreeSpaceBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("InventoryRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("VolumeKey")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId", "InventoryRunId")
                        .HasDatabaseName("IX_WindowsVolumeInventory_ManagedServer_InventoryRun");

                    b.HasIndex("ManagedServerId", "VolumeKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsVolumeInventory_ManagedServer_VolumeKey");

                    b.ToTable("WindowsVolumeInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorDecisionCapabilityReference", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.CollectorStrategyDecision", null)
                        .WithMany("CapabilityReferences")
                        .HasForeignKey("StrategyDecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorDecisionPlan", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorHeartbeat", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.CollectorNode", null)
                        .WithMany()
                        .HasForeignKey("CollectorNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CollectorHeartbeat_CollectorNode_CollectorNodeId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorRun", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.CollectorNode", null)
                        .WithMany()
                        .HasForeignKey("CollectorNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CollectorRun_CollectorNode_CollectorNodeId");

                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CollectorRun_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorStrategyDecision", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.CollectorDecisionPlan", null)
                        .WithMany("Strategies")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CommandQueueItem", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CommandQueueItem_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.ExecutionPlan", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.ExecutionPlanExclusion", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ExecutionPlan", null)
                        .WithMany("Exclusions")
                        .HasForeignKey("ExecutionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.ExecutionPlanExclusionCapability", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ExecutionPlanExclusion", null)
                        .WithMany("Capabilities")
                        .HasForeignKey("ExclusionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.ExecutionPlanStep", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ExecutionPlan", null)
                        .WithMany("Steps")
                        .HasForeignKey("ExecutionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.InventorySnapshot", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.CollectorRun", null)
                        .WithMany()
                        .HasForeignKey("CollectorRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventorySnapshot_CollectorRun_CollectorRunId");

                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventorySnapshot_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsBiosInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithOne()
                        .HasForeignKey("PSMOperationsPlatform.Domain.Entities.WindowsBiosInventory", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsBiosInventory_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsCapabilityEntry", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.WindowsCapabilitySnapshot", null)
                        .WithMany("Entries")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsCapabilityProvenance", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.WindowsCapabilityEntry", null)
                        .WithMany("Provenance")
                        .HasForeignKey("CapabilityEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsCapabilitySnapshot", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsComputerInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithOne()
                        .HasForeignKey("PSMOperationsPlatform.Domain.Entities.WindowsComputerInventory", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsComputerInventory_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsDiskInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsDiskInventory_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsDotNetPlatformInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsFeatureInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsIisPlatformInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsIpv4AddressInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsIpv4AddressInventory_ManagedServer_ManagedServerId");

                    b.HasOne("PSMOperationsPlatform.Domain.Entities.WindowsNetworkAdapterInventory", null)
                        .WithMany()
                        .HasForeignKey("NetworkAdapterInventoryId", "ManagedServerId")
                        .HasPrincipalKey("Id", "ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsIpv4AddressInventory_WindowsNetworkAdapterInventory_NetworkAdapterInventoryId_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsMemoryInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsMemoryInventory_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsNetworkAdapterInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsNetworkAdapterInventory_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsOperatingSystemInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithOne()
                        .HasForeignKey("PSMOperationsPlatform.Domain.Entities.WindowsOperatingSystemInventory", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsOperatingSystemInventory_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsPowerShellPlatformInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsProcessorInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsProcessorInventory_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsRoleInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsVolumeInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsVolumeInventory_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorDecisionPlan", b =>
                {
                    b.Navigation("Strategies");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorStrategyDecision", b =>
                {
                    b.Navigation("CapabilityReferences");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.ExecutionPlan", b =>
                {
                    b.Navigation("Exclusions");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.ExecutionPlanExclusion", b =>
                {
                    b.Navigation("Capabilities");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsCapabilityEntry", b =>
                {
                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsCapabilitySnapshot", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
