// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSMOperationsPlatform.Infrastructure.Persistence;

#nullable disable

namespace PSMOperationsPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OperationsDbContext))]
    partial class OperationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetailJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditLog_CorrelationId");

                    b.HasIndex("OccurredAt")
                        .IsDescending()
                        .HasDatabaseName("IX_AuditLog_OccurredAt");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_AuditLog_Entity");

                    b.ToTable("AuditLog", "audit", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_DetailJson_IsJson", "[DetailJson] IS NULL OR ISJSON([DetailJson]) = 1");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorHeartbeat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollectorNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long?>("WorkingSetBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CollectorNodeId", "ObservedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_CollectorHeartbeat_Collector_ObservedAt");

                    b.ToTable("CollectorHeartbeat", "monitoring");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HostFqdn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InstanceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HostFqdn", "CollectorType", "InstanceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectorNode_Registration");

                    b.ToTable("CollectorNode", "collection");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CollectorNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_CollectorRun_Server_CreatedAt");

                    b.HasIndex("CollectorNodeId", "Status", "CreatedAt")
                        .HasDatabaseName("IX_CollectorRun_Collector_Status_CreatedAt");

                    b.ToTable("CollectorRun", "collection");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CommandQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NotBefore")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TargetCollectorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId");

                    b.HasIndex("Status", "TargetCollectorType", "Priority", "NotBefore", "CreatedAt")
                        .HasDatabaseName("IX_CommandQueue_Status_Target_Priority");

                    b.ToTable("CommandQueueItem", "operations", t =>
                        {
                            t.HasCheckConstraint("CK_CommandQueueItem_PayloadJson_IsJson", "ISJSON([PayloadJson]) = 1");

                            t.HasCheckConstraint("CK_CommandQueueItem_Priority_NonNegative", "[Priority] >= 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.InventorySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CollectorRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("char(64)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CollectorRunId", "SnapshotType", "SchemaVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_InventorySnapshot_RunContract");

                    b.HasIndex("ManagedServerId", "SnapshotType", "CapturedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_InventorySnapshot_Server_Type_CapturedAt");

                    b.ToTable("InventorySnapshot", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_InventorySnapshot_PayloadJson_IsJson", "ISJSON([PayloadJson]) = 1");

                            t.HasCheckConstraint("CK_InventorySnapshot_SchemaVersion_Positive", "[SchemaVersion] > 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsComputerInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ManagedServerId");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ComputerName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DomainName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Fqdn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Model")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("WindowsComputerInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsDiskInventory", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<string>("BusType").HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<DateTime>("CapturedAt").HasColumnType("datetime2(3)");
                    b.Property<int?>("DiskNumber").HasColumnType("int");
                    b.Property<string>("FriendlyName").HasMaxLength(255).HasColumnType("nvarchar(255)");
                    b.Property<Guid>("ManagedServerId").HasColumnType("uniqueidentifier");
                    b.Property<string>("PartitionStyle").HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("SerialNumber").HasMaxLength(255).HasColumnType("nvarchar(255)");
                    b.Property<long?>("SizeBytes").HasColumnType("bigint");
                    b.Property<string>("StableSourceKey").IsRequired().HasMaxLength(260).HasColumnType("nvarchar(260)");

                    b.HasKey("Id");
                    b.HasIndex("ManagedServerId", "StableSourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsDiskInventory_ManagedServer_StableSourceKey");
                    b.ToTable("WindowsDiskInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsIpv4AddressInventory", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<string>("Address").IsRequired().HasMaxLength(15).HasColumnType("nvarchar(15)");
                    b.Property<DateTime>("CapturedAt").HasColumnType("datetime2(3)");
                    b.Property<bool?>("IsDhcp").HasColumnType("bit");
                    b.Property<Guid>("ManagedServerId").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("NetworkAdapterInventoryId").HasColumnType("uniqueidentifier");
                    b.Property<int>("PrefixLength").HasColumnType("int");
                    b.Property<string>("StableSourceKey").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");

                    b.HasKey("Id");
                    b.HasIndex("NetworkAdapterInventoryId")
                        .HasDatabaseName("IX_WindowsIpv4AddressInventory_NetworkAdapterInventoryId");
                    b.HasIndex("ManagedServerId", "StableSourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsIpv4AddressInventory_ManagedServer_StableSourceKey");
                    b.ToTable("WindowsIpv4AddressInventory", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_WindowsIpv4AddressInventory_PrefixLength_Range", "[PrefixLength] >= 0 AND [PrefixLength] <= 32");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsMemoryInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ManagedServerId");
                    b.Property<DateTime>("CapturedAt").HasColumnType("datetime2(3)");
                    b.Property<long>("TotalPhysicalMemoryBytes").HasColumnType("bigint");

                    b.HasKey("Id");
                    b.ToTable("WindowsMemoryInventory", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_WindowsMemoryInventory_TotalPhysicalMemoryBytes_NonNegative", "[TotalPhysicalMemoryBytes] >= 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsNetworkAdapterInventory", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CapturedAt").HasColumnType("datetime2(3)");
                    b.Property<string>("InterfaceDescription").HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<long?>("LinkSpeedBitsPerSecond").HasColumnType("bigint");
                    b.Property<string>("MacAddress").HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<Guid>("ManagedServerId").HasColumnType("uniqueidentifier");
                    b.Property<string>("Name").HasMaxLength(255).HasColumnType("nvarchar(255)");
                    b.Property<string>("OperationalStatus").HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("StableSourceKey").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");

                    b.HasKey("Id");
                    b.HasIndex("ManagedServerId", "StableSourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsNetworkAdapterInventory_ManagedServer_StableSourceKey");
                    b.ToTable("WindowsNetworkAdapterInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsOperatingSystemInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ManagedServerId");
                    b.Property<string>("Architecture").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("BuildNumber").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<DateTime>("CapturedAt").HasColumnType("datetime2(3)");
                    b.Property<string>("Caption").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)");
                    b.Property<string>("Edition").HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<DateTime?>("InstallDate").HasColumnType("datetime2(3)");
                    b.Property<DateTime?>("LastBootTime").HasColumnType("datetime2(3)");
                    b.Property<string>("TimeZoneId").HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Version").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");

                    b.HasKey("Id");
                    b.ToTable("WindowsOperatingSystemInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsProcessorInventory", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CapturedAt").HasColumnType("datetime2(3)");
                    b.Property<int?>("CoreCount").HasColumnType("int");
                    b.Property<int?>("LogicalProcessorCount").HasColumnType("int");
                    b.Property<Guid>("ManagedServerId").HasColumnType("uniqueidentifier");
                    b.Property<string>("Manufacturer").HasMaxLength(255).HasColumnType("nvarchar(255)");
                    b.Property<int?>("MaxClockSpeedMhz").HasColumnType("int");
                    b.Property<string>("Name").HasMaxLength(255).HasColumnType("nvarchar(255)");
                    b.Property<string>("StableSourceKey").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");

                    b.HasKey("Id");
                    b.HasIndex("ManagedServerId", "StableSourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsProcessorInventory_ManagedServer_StableSourceKey");
                    b.ToTable("WindowsProcessorInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsVolumeInventory", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CapturedAt").HasColumnType("datetime2(3)");
                    b.Property<string>("DriveLetter").HasMaxLength(10).HasColumnType("nvarchar(10)");
                    b.Property<string>("FileSystem").HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<long?>("FreeSpaceBytes").HasColumnType("bigint");
                    b.Property<string>("Label").HasMaxLength(255).HasColumnType("nvarchar(255)");
                    b.Property<Guid>("ManagedServerId").HasColumnType("uniqueidentifier");
                    b.Property<long?>("SizeBytes").HasColumnType("bigint");
                    b.Property<string>("StableSourceKey").IsRequired().HasMaxLength(260).HasColumnType("nvarchar(260)");

                    b.HasKey("Id");
                    b.HasIndex("ManagedServerId", "StableSourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_WindowsVolumeInventory_ManagedServer_StableSourceKey");
                    b.ToTable("WindowsVolumeInventory", "inventory");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.ManagedServer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("ConsecutiveConnectivityFailures")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Environment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fqdn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastConnectivityAttemptAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LastConnectivityFailureCategory")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastConnectivityState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("LastConnectivitySuccessAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LastSuccessfulTransport")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NextConnectivityAttemptAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("WinRmHttpPort")
                        .HasColumnType("int");

                    b.Property<int>("WinRmHttpsPort")
                        .HasColumnType("int");

                    b.Property<int>("WinRmProbeTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<string>("WinRmTransportMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled", "NextConnectivityAttemptAt")
                        .HasDatabaseName("IX_ManagedServer_Eligibility");

                    b.HasIndex("Fqdn")
                        .IsUnique()
                        .HasDatabaseName("UX_ManagedServer_Fqdn");

                    b.ToTable("ManagedServer", "configuration", t =>
                        {
                            t.HasCheckConstraint("CK_ManagedServer_ConnectivityFailures_NonNegative", "[ConsecutiveConnectivityFailures] >= 0");

                            t.HasCheckConstraint("CK_ManagedServer_LastConnectivityState", "[LastConnectivityState] IN ('Unknown', 'Reachable', 'Unreachable')");

                            t.HasCheckConstraint("CK_ManagedServer_LastConnectivityFailureCategory", "[LastConnectivityFailureCategory] IS NULL OR [LastConnectivityFailureCategory] IN ('DnsFailure', 'ConnectionRefused', 'Timeout', 'TlsFailure', 'AuthenticationFailure', 'AuthorizationFailure', 'WinRmUnavailable', 'ProtocolFailure', 'Unexpected')");

                            t.HasCheckConstraint("CK_ManagedServer_LastSuccessfulTransport", "[LastSuccessfulTransport] IS NULL OR [LastSuccessfulTransport] IN ('Https', 'Http')");

                            t.HasCheckConstraint("CK_ManagedServer_WinRmHttpPort_Range", "[WinRmHttpPort] >= 1 AND [WinRmHttpPort] <= 65535");

                            t.HasCheckConstraint("CK_ManagedServer_WinRmHttpsPort_Range", "[WinRmHttpsPort] >= 1 AND [WinRmHttpsPort] <= 65535");

                            t.HasCheckConstraint("CK_ManagedServer_WinRmProbeTimeout_Positive", "[WinRmProbeTimeoutSeconds] > 0");

                            t.HasCheckConstraint("CK_ManagedServer_WinRmTransportMode", "[WinRmTransportMode] IN ('Auto', 'HttpsOnly', 'HttpOnly')");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorHeartbeat", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.CollectorNode", null)
                        .WithMany()
                        .HasForeignKey("CollectorNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CollectorHeartbeat_CollectorNode_CollectorNodeId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorRun", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.CollectorNode", null)
                        .WithMany()
                        .HasForeignKey("CollectorNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CollectorRun_CollectorNode_CollectorNodeId");

                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CollectorRun_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CommandQueueItem", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CommandQueueItem_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.InventorySnapshot", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.CollectorRun", null)
                        .WithMany()
                        .HasForeignKey("CollectorRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventorySnapshot_CollectorRun_CollectorRunId");

                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventorySnapshot_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsComputerInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithOne()
                        .HasForeignKey("PSMOperationsPlatform.Domain.Entities.WindowsComputerInventory", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsComputerInventory_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsDiskInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsDiskInventory_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsIpv4AddressInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsIpv4AddressInventory_ManagedServer_ManagedServerId");

                    b.HasOne("PSMOperationsPlatform.Domain.Entities.WindowsNetworkAdapterInventory", null)
                        .WithMany()
                        .HasForeignKey("NetworkAdapterInventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsIpv4AddressInventory_WindowsNetworkAdapterInventory_NetworkAdapterInventoryId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsMemoryInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithOne()
                        .HasForeignKey("PSMOperationsPlatform.Domain.Entities.WindowsMemoryInventory", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsMemoryInventory_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsNetworkAdapterInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsNetworkAdapterInventory_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsOperatingSystemInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithOne()
                        .HasForeignKey("PSMOperationsPlatform.Domain.Entities.WindowsOperatingSystemInventory", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsOperatingSystemInventory_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsProcessorInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsProcessorInventory_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.WindowsVolumeInventory", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WindowsVolumeInventory_ManagedServer_ManagedServerId");
                });
#pragma warning restore 612, 618
        }
    }
}
