// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSMOperationsPlatform.Infrastructure.Persistence;

#nullable disable

namespace PSMOperationsPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OperationsDbContext))]
    partial class OperationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetailJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditLog_CorrelationId");

                    b.HasIndex("OccurredAt")
                        .IsDescending()
                        .HasDatabaseName("IX_AuditLog_OccurredAt");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_AuditLog_Entity");

                    b.ToTable("AuditLog", "audit", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_DetailJson_IsJson", "[DetailJson] IS NULL OR ISJSON([DetailJson]) = 1");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorHeartbeat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollectorNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long?>("WorkingSetBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CollectorNodeId", "ObservedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_CollectorHeartbeat_Collector_ObservedAt");

                    b.ToTable("CollectorHeartbeat", "monitoring");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HostFqdn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InstanceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HostFqdn", "CollectorType", "InstanceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectorNode_Registration");

                    b.ToTable("CollectorNode", "collection");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CollectorNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_CollectorRun_Server_CreatedAt");

                    b.HasIndex("CollectorNodeId", "Status", "CreatedAt")
                        .HasDatabaseName("IX_CollectorRun_Collector_Status_CreatedAt");

                    b.ToTable("CollectorRun", "collection");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CommandQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NotBefore")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TargetCollectorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedServerId");

                    b.HasIndex("Status", "TargetCollectorType", "Priority", "NotBefore", "CreatedAt")
                        .HasDatabaseName("IX_CommandQueue_Status_Target_Priority");

                    b.ToTable("CommandQueueItem", "operations", t =>
                        {
                            t.HasCheckConstraint("CK_CommandQueueItem_PayloadJson_IsJson", "ISJSON([PayloadJson]) = 1");

                            t.HasCheckConstraint("CK_CommandQueueItem_Priority_NonNegative", "[Priority] >= 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.InventorySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CollectorRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagedServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("char(64)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CollectorRunId", "SnapshotType", "SchemaVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_InventorySnapshot_RunContract");

                    b.HasIndex("ManagedServerId", "SnapshotType", "CapturedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_InventorySnapshot_Server_Type_CapturedAt");

                    b.ToTable("InventorySnapshot", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_InventorySnapshot_PayloadJson_IsJson", "ISJSON([PayloadJson]) = 1");

                            t.HasCheckConstraint("CK_InventorySnapshot_SchemaVersion_Positive", "[SchemaVersion] > 0");
                        });
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.ManagedServer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Environment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fqdn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("Fqdn")
                        .IsUnique()
                        .HasDatabaseName("UX_ManagedServer_Fqdn");

                    b.ToTable("ManagedServer", "configuration");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorHeartbeat", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.CollectorNode", null)
                        .WithMany()
                        .HasForeignKey("CollectorNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CollectorHeartbeat_CollectorNode_CollectorNodeId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CollectorRun", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.CollectorNode", null)
                        .WithMany()
                        .HasForeignKey("CollectorNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CollectorRun_CollectorNode_CollectorNodeId");

                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CollectorRun_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.CommandQueueItem", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CommandQueueItem_ManagedServer_ManagedServerId");
                });

            modelBuilder.Entity("PSMOperationsPlatform.Domain.Entities.InventorySnapshot", b =>
                {
                    b.HasOne("PSMOperationsPlatform.Domain.Entities.CollectorRun", null)
                        .WithMany()
                        .HasForeignKey("CollectorRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventorySnapshot_CollectorRun_CollectorRunId");

                    b.HasOne("PSMOperationsPlatform.Domain.Entities.ManagedServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventorySnapshot_ManagedServer_ManagedServerId");
                });
#pragma warning restore 612, 618
        }
    }
}
