#requires -Version 5.1
Set-StrictMode -Version Latest

function New-SqlCheck {
    param([string]$Prefix,[string]$Id,[string]$Category,[string]$Name,[string]$Target,
        [object]$Actual,[string]$Status='PASS',[string]$Severity='INFO',[object]$Expected='observe',
        [string]$Message='Value observed.',[string]$Recommendation=$null,[bool]$Mandatory=$false)
    New-OperationalObservation "$Prefix.$Id" $Category $Name $Name $Target $Status $Severity `
        $Expected $Actual $Message $Recommendation $Actual $Mandatory
}

function ConvertTo-SqlRows {
    param([Parameter(Mandatory)][Data.SqlClient.SqlDataReader]$Reader)
    $rows=New-Object Collections.Generic.List[object]
    while($Reader.Read()){$row=[ordered]@{};for($index=0;$index -lt $Reader.FieldCount;$index++){$value=$Reader.GetValue($index);$row[$Reader.GetName($index)]=if($value -is [DBNull]){$null}else{$value}};$rows.Add([pscustomobject]$row)}
    $rows.ToArray()
}

function Invoke-SqlTargetReadOnlyQuery {
    param([Data.SqlClient.SqlConnection]$Connection,[string]$Text,[hashtable]$Parameters=@{})
    if(-not (Test-SqlTargetQuerySafety $Text)){throw 'Unsafe SQL query was rejected before execution.'}
    $command=$Connection.CreateCommand();$command.CommandText=$Text;$command.CommandTimeout=15
    try{foreach($name in $Parameters.Keys){[void]$command.Parameters.AddWithValue($name,$Parameters[$name])};$reader=$command.ExecuteReader();try{return @(ConvertTo-SqlRows $reader)}finally{$reader.Dispose()}}
    finally{$command.Dispose()}
}

function Invoke-SqlTargetReleaseValidator {
    param([object]$Target,[string]$Database,[string]$ScriptPath,[string[]]$Variables)
    $sqlcmd=Get-Command sqlcmd.exe -ErrorAction SilentlyContinue
    if($null -eq $sqlcmd){throw 'sqlcmd.exe is unavailable for the approved release validator.'}
    $arguments=@('-S',"$($Target.Server),$($Target.Port)",'-d',$Database,'-E','-N','-b','-V','16')
    if($Variables.Count){$arguments+='-v';$arguments+=$Variables}
    $arguments+=@('-i',$ScriptPath)
    $output=@(& $sqlcmd.Source @arguments 2>&1);if($LASTEXITCODE -ne 0){throw "Approved release validator failed: $($output -join ' ')"}
    if(($output -join [Environment]::NewLine) -notmatch '(?im)^PASS\s*$|OverallResult\s+PASS'){throw 'Approved release validator did not return PASS.'}
    'PASS'
}

function New-SqlTargetValidationOperations {
    [CmdletBinding()]param()
    $repositoryRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
    @{
        ResolveDns={param($name)@(Resolve-OperationalDns $name)}
        ResolveReverseDns={param($address)([Net.Dns]::GetHostEntry($address)).HostName}
        TestTcp={param($name,$port)Test-OperationalTcpPort $name $port}
        GetRoute={param($address)$route=Get-NetRoute -AddressFamily IPv4 -ErrorAction Stop|Sort-Object RouteMetric,InterfaceMetric|Select-Object -First 1;[pscustomobject]@{InterfaceIndex=$route.InterfaceIndex;RouteMetric=$route.RouteMetric}}
        GetSpn={param($spn)if(Get-Command setspn.exe -ErrorAction SilentlyContinue){@(& setspn.exe -Q $spn 2>&1)}else{throw 'setspn.exe is unavailable.'}}
        OpenConnection={param($target)
            $builder=[Data.SqlClient.SqlConnectionStringBuilder]::new()
            $builder['Data Source']="$($target.Server),$($target.Port)";$builder['Initial Catalog']='master'
            $builder['Integrated Security']=$true;$builder['Encrypt']=[bool]$target.Encrypt
            $builder['TrustServerCertificate']=[bool]$target.TrustServerCertificate
            $builder['Connect Timeout']=10;$builder['Application Name']='PSM Operations SQL Target Validation'
            $builder['ApplicationIntent']='ReadOnly';$connection=[Data.SqlClient.SqlConnection]::new($builder.ConnectionString)
            $connection.Open();$connection
        }
        Query={param($connection,$text,$parameters)@(Invoke-SqlTargetReadOnlyQuery $connection $text $parameters)}
        CloseConnection={param($connection)if($null -ne $connection){$connection.Dispose()}}
        RunSchemaValidation=({param($target,$configuration)
            $path=Join-Path $repositoryRoot 'Release\Database\SchemaValidation.sql'
            Invoke-SqlTargetReleaseValidator $target $configuration.SqlServer.Database $path @(
                "ExpectedDatabaseName=$($configuration.SqlServer.Database)",
                "ExpectedCompatibilityLevel=$($configuration.SqlServer.CompatibilityLevel)",
                "ExpectedCollation=$($configuration.SqlServer.Collation)",
                "ExpectedRecoveryModel=$($configuration.SqlServer.RecoveryModel)",
                'ExpectedSchemaVersion=20260729191745_WP0088ExecutionHistory')
        }).GetNewClosure()
        RunPermissionValidation=({param($target,$configuration)
            $path=Join-Path $repositoryRoot 'Release\Database\PermissionValidation.sql'
            Invoke-SqlTargetReleaseValidator $target $configuration.SqlServer.Database $path @(
                "CollectorPrincipal=$($configuration.Collector.ServiceAccount)",
                "PortalPrincipal=$($configuration.Portal.ServiceAccount)",
                "SqlCollectorPrincipal=$($configuration.SqlCollector.ServiceAccount)")
        }).GetNewClosure()
    }
}

function Invoke-SqlQuerySafe {
    param([hashtable]$Operations,[object]$Connection,[string]$Text,[hashtable]$Parameters,[string]$Name)
    try{[pscustomobject]@{Succeeded=$true;Rows=@(& $Operations.Query $Connection $Text $Parameters);Error=$null}}
    catch{[pscustomobject]@{Succeeded=$false;Rows=@();Error=(Protect-OperationalText $_.Exception.Message);Name=$Name}}
}

function New-SqlRemoteSkippedChecks {
    param([string]$Prefix,[string]$Target,[string]$Reason)
    foreach($item in @(@('IDENTITY','SQLServerIdentityVersion'),@('SERVICE','SQLServiceProtocol'),@('KERBEROS','KerberosSPN'),@('TLS','EncryptionTLS'),@('CONFIG','ServerConfiguration'),@('DATABASES','DatabaseInventory'),@('OPERATIONS','OperationsDatabaseCompatibility'),@('PERMISSIONS','CollectorMetadataPermissions'),@('PERFORMANCE','PerformanceMetadataAvailability'),@('FILES','DatabaseFileCapacity'),@('BACKUP','BackupRecoveryObservability'),@('AVAILABILITY','AvailabilityFeatures'),@('SECURITY','SecurityPosture'))){New-SqlCheck $Prefix "$($item[0]).SKIPPED" $item[1] 'Dependent checks skipped' $Target $null SKIPPED MEDIUM 'successful SQL connection' $Reason 'Resolve connection prerequisites and rerun.' $true}
}

function Invoke-SqlTargetChecks {
    [CmdletBinding()]
    param([object]$Configuration,[object]$SqlTarget,[int]$TargetIndex,[string]$ComputerName,[bool]$SkipDatabaseChecks,[bool]$SkipPermissionChecks,[hashtable]$Operations)
    $prefix='T{0:D3}' -f $TargetIndex;$targetName=[string]$SqlTarget.Name;$results=New-Object Collections.Generic.List[object]
    $connection=$null;$connected=$false;$core=$null;$queries=Get-SqlTargetValidationQueries
    try{
        $results.Add((New-SqlCheck $prefix 'TARGET.DEFINITION' TargetConfiguration 'Configured SQL target' $targetName "$($SqlTarget.Server)\$($SqlTarget.Instance):$($SqlTarget.Port)" PASS INFO 'valid enabled configuration' 'Configuration passed the shared validator.' $null $true))
        if(-not $SqlTarget.ValidationEnabled){$results.Add((New-SqlCheck $prefix 'TARGET.ENABLED' TargetConfiguration 'Validation enabled' $targetName $false NOT_APPLICABLE INFO $true 'Disabled target was not contacted.'));return $results.ToArray()}
        $results.Add((New-SqlCheck $prefix 'TARGET.ENABLED' TargetConfiguration 'Validation enabled' $targetName $true PASS INFO $true 'Target is enabled.'))
        try{$addresses=@(@(& $Operations.ResolveDns $SqlTarget.Server)|Sort-Object -Unique);$ok=$addresses.Count -gt 0;$results.Add((New-SqlCheck $prefix 'NETWORK.DNS.FORWARD' DNSNetworkConnectivity 'Forward DNS' $targetName ($addresses -join ',') $(if($ok){'PASS'}else{'FAIL'}) $(if($ok){'INFO'}else{'HIGH'}) 'resolved address' 'Configured server resolution.' 'Correct approved DNS records.' $true));if($ok){try{$reverse=& $Operations.ResolveReverseDns $addresses[0];$results.Add((New-SqlCheck $prefix 'NETWORK.DNS.REVERSE' DNSNetworkConnectivity 'Reverse DNS' $targetName $reverse))}catch{$results.Add((New-SqlCheck $prefix 'NETWORK.DNS.REVERSE' DNSNetworkConnectivity 'Reverse DNS' $targetName 'unavailable' WARNING LOW 'reverse name when available' 'Reverse lookup unavailable.' 'Review PTR records where required.'))};try{$route=& $Operations.GetRoute $addresses[0];$results.Add((New-SqlCheck $prefix 'NETWORK.ROUTE' DNSNetworkConnectivity 'Source route' $targetName "Interface=$($route.InterfaceIndex); Metric=$($route.RouteMetric)"))}catch{$results.Add((New-SqlCheck $prefix 'NETWORK.ROUTE' DNSNetworkConnectivity 'Source route' $targetName 'unavailable' WARNING LOW 'bounded route observation' 'Route diagnostics unavailable.'))}}}catch{$results.Add((New-OperationalExceptionResult "$prefix.NETWORK.DNS.FORWARD" DNSNetworkConnectivity 'Forward DNS' 'Resolve configured SQL target.' $targetName $_.Exception HIGH $true));$addresses=@()}
        try{$tcp=[bool](& $Operations.TestTcp $SqlTarget.Server ([int]$SqlTarget.Port));$results.Add((New-SqlCheck $prefix 'NETWORK.TCP' DNSNetworkConnectivity 'Configured SQL TCP port' $targetName $tcp $(if($tcp){'PASS'}else{'FAIL'}) $(if($tcp){'INFO'}else{'HIGH'}) $true 'Only the configured endpoint was tested.' 'Correct approved network/listener configuration.' $true))}catch{$results.Add((New-OperationalExceptionResult "$prefix.NETWORK.TCP" DNSNetworkConnectivity 'Configured SQL TCP port' 'Test configured SQL endpoint.' $targetName $_.Exception HIGH $true))}
        try{$connection=& $Operations.OpenConnection $SqlTarget;$connected=$null -ne $connection;$results.Add((New-SqlCheck $prefix 'CONNECTION.OPEN' SQLConnection 'Windows Integrated SQL connection' $targetName $connected $(if($connected){'PASS'}else{'FAIL'}) $(if($connected){'INFO'}else{'CRITICAL'}) $true 'Bounded current-identity connection.' 'Correct endpoint, identity, TLS, or SQL availability.' $true))}catch{$message=Protect-OperationalText $_.Exception.Message;$timeout=$message -match '(?i)timeout|timed out';$results.Add((New-SqlCheck $prefix 'CONNECTION.OPEN' SQLConnection 'Windows Integrated SQL connection' $targetName $(if($timeout){'timeout'}else{'failed'}) FAIL CRITICAL 'successful bounded connection' 'SQL connection failed.' 'Correct endpoint, identity, TLS, or SQL availability.' $true))}
        if(-not $connected){foreach($item in @(New-SqlRemoteSkippedChecks $prefix $targetName 'SQL connection was not established.')){$results.Add($item)}}else{
            $coreResult=Invoke-SqlQuerySafe $Operations $connection $queries.CoreMetadata @{} CoreMetadata;if($coreResult.Succeeded -and $coreResult.Rows.Count){$core=$coreResult.Rows[0]}else{$results.Add((New-SqlCheck $prefix 'CONNECTION.METADATA' SQLConnection 'Connection metadata' $targetName $coreResult.Error FAIL HIGH 'metadata row' 'Required connection metadata unavailable.' 'Grant documented metadata access.' $true))}
            if($core){
                $windows=[string]$core.LoginName -match '\\';$results.Add((New-SqlCheck $prefix 'CONNECTION.WINDOWSAUTH' SQLConnection 'Windows Authentication identity' $targetName $core.LoginName $(if($windows){'PASS'}else{'FAIL'}) $(if($windows){'INFO'}else{'CRITICAL'}) 'domain-qualified Windows identity' 'Current SQL login observed.' 'Run under the approved SQL Collector identity.' $true))
                $endpointOk=([string]$core.InstanceName -eq [string]$SqlTarget.Instance) -and (($null -eq $core.local_tcp_port) -or ([int]$core.local_tcp_port -eq [int]$SqlTarget.Port));$results.Add((New-SqlCheck $prefix 'CONNECTION.ENDPOINT' SQLConnection 'Connected endpoint' $targetName "$($core.ServerName);$($core.InstanceName);$($core.local_tcp_port)" $(if($endpointOk){'PASS'}else{'FAIL'}) $(if($endpointOk){'INFO'}else{'HIGH'}) "$($SqlTarget.Instance):$($SqlTarget.Port)" 'Actual endpoint compared.' 'Correct static endpoint or configuration.' $true))
                foreach($item in @(@('IDENTITY.SERVER','Server identity',$core.ServerName),@('IDENTITY.MACHINE','Machine identity',$core.MachineName),@('IDENTITY.INSTANCE','Instance identity',$core.InstanceName),@('IDENTITY.VERSION','Product version',$core.ProductVersion),@('IDENTITY.LEVEL','Product level',$core.ProductLevel),@('IDENTITY.EDITION','Edition',$core.Edition),@('IDENTITY.ENGINE','Engine edition',$core.EngineEdition),@('IDENTITY.CLUSTER','Clustered',$core.IsClustered),@('IDENTITY.HADR','Always On capable',$core.IsHadrEnabled))){$status='PASS';if($item[0] -eq 'IDENTITY.VERSION' -and $SqlTarget.PSObject.Properties['ExpectedVersion'] -and -not ([string]$item[2]).StartsWith([string]$SqlTarget.ExpectedVersion)){$status='FAIL'};if($item[0] -eq 'IDENTITY.EDITION' -and $SqlTarget.PSObject.Properties['ExpectedEdition'] -and [string]$item[2] -ne [string]$SqlTarget.ExpectedEdition){$status='FAIL'};$results.Add((New-SqlCheck $prefix $item[0] SQLServerIdentityVersion $item[1] $targetName $item[2] $status $(if($status -eq 'PASS'){'INFO'}else{'HIGH'}) 'configured expectation or observation'))}
                $platform=Invoke-SqlQuerySafe $Operations $connection $queries.HostPlatform @{} HostPlatform;$results.Add((New-SqlCheck $prefix 'IDENTITY.PLATFORM' SQLServerIdentityVersion 'Host platform' $targetName $(if($platform.Succeeded -and $platform.Rows.Count){"$($platform.Rows[0].host_platform);$($platform.Rows[0].host_distribution);$($platform.Rows[0].host_release)"}else{'unavailable'}) $(if($platform.Succeeded){'PASS'}else{'WARNING'}) LOW 'when supported'))
                $protocol=[string]$core.net_transport;$results.Add((New-SqlCheck $prefix 'SERVICE.PROTOCOL' SQLServiceProtocol 'Active session protocol' $targetName $protocol $(if($protocol -eq 'TCP'){'PASS'}else{'FAIL'}) $(if($protocol -eq 'TCP'){'INFO'}else{'HIGH'}) 'TCP' 'Active transport observed.' 'Enable/correct through approved change control.' $true));$results.Add((New-SqlCheck $prefix 'SERVICE.REMOTE' SQLServiceProtocol 'Service and registry metadata' $targetName 'not queried without separately approved remote access' SKIPPED LOW 'optional read-only remote evidence' 'SQL session metadata remains authoritative for this run.'))
                $kerberos=[string]$core.auth_scheme -eq 'KERBEROS';$results.Add((New-SqlCheck $prefix 'KERBEROS.AUTHSCHEME' KerberosSPN 'Kerberos authentication' $targetName $core.auth_scheme $(if($kerberos){'PASS'}else{'FAIL'}) $(if($kerberos){'INFO'}else{'CRITICAL'}) 'KERBEROS' 'Authentication scheme observed.' 'Correct SPN, DNS, service account, or delegation; do not permit downgrade.' $true));$fqdn=if($addresses.Count){try{(& $Operations.ResolveReverseDns $addresses[0])}catch{$SqlTarget.Server}}else{$SqlTarget.Server};$spn="MSSQLSvc/$fqdn`:$($SqlTarget.Port)";$results.Add((New-SqlCheck $prefix 'KERBEROS.SPN.EXPECTED' KerberosSPN 'Expected MSSQLSvc SPN' $targetName $spn));try{$spnEvidence=@(& $Operations.GetSpn $spn);$results.Add((New-SqlCheck $prefix 'KERBEROS.SPN.QUERY' KerberosSPN 'SPN query' $targetName "$($spnEvidence.Count) output line(s)" PASS INFO 'read-only directory query'))}catch{$results.Add((New-SqlCheck $prefix 'KERBEROS.SPN.QUERY' KerberosSPN 'SPN query' $targetName 'unavailable' WARNING LOW 'read-only directory query when permitted' 'SPN tooling or permission unavailable.' 'Have an authorized AD operator review the expected SPN.'))}
                $encrypted=[string]$core.encrypt_option -eq 'TRUE';$results.Add((New-SqlCheck $prefix 'TLS.ENCRYPTED' EncryptionTLS 'Active connection encryption' $targetName $core.encrypt_option $(if($encrypted){'PASS'}else{'FAIL'}) $(if($encrypted){'INFO'}else{'CRITICAL'}) 'TRUE' 'Encryption state observed.' 'Correct SQL TLS/certificate configuration without bypass.' $true));$results.Add((New-SqlCheck $prefix 'TLS.TRUST' EncryptionTLS 'Certificate trust policy' $targetName $SqlTarget.TrustServerCertificate $(if(-not $SqlTarget.TrustServerCertificate){'PASS'}else{'FAIL'}) HIGH $false 'Certificate validation policy configured.'))
                $serverConfig=Invoke-SqlQuerySafe $Operations $connection $queries.ServerConfiguration @{} ServerConfiguration;if($serverConfig.Succeeded){$number=0;foreach($row in @($serverConfig.Rows|Sort-Object name)){$number++;$results.Add((New-SqlCheck $prefix ('CONFIG.ITEM.{0:D2}' -f $number) ServerConfiguration $row.name $targetName $row.ValueInUse))}}else{$results.Add((New-SqlCheck $prefix 'CONFIG.UNAVAILABLE' ServerConfiguration 'Server configuration metadata' $targetName $serverConfig.Error WARNING LOW 'informational when accessible'))}

                $databaseParameter=@($SqlTarget.DatabasesToValidate)-join [char]31
                if($SkipDatabaseChecks){foreach($item in @(@('DATABASES','DatabaseInventory'),@('OPERATIONS','OperationsDatabaseCompatibility'),@('FILES','DatabaseFileCapacity'),@('BACKUP','BackupRecoveryObservability'))){$results.Add((New-SqlCheck $prefix "$($item[0]).SKIPPED" $item[1] 'Database checks skipped' $targetName $null SKIPPED MEDIUM 'operator-enabled database checks' 'SkipDatabaseChecks was supplied.' $null $true))}}
                else{
                    $databases=Invoke-SqlQuerySafe $Operations $connection $queries.DatabaseInventory @{'@DatabaseNames'=$databaseParameter} DatabaseInventory;if($databases.Succeeded){foreach($database in $SqlTarget.DatabasesToValidate){$row=@($databases.Rows|Where-Object name -eq $database|Select-Object -First 1);if($row.Count){$value=$row[0];$results.Add((New-SqlCheck $prefix ('DATABASES.ITEM.{0:D3}' -f ([array]::IndexOf(@($SqlTarget.DatabasesToValidate),$database)+1)) DatabaseInventory 'Configured database' $targetName "Name=$($value.name); State=$($value.state_desc); Access=$($value.user_access_desc); ReadOnly=$($value.is_read_only); Recovery=$($value.recovery_model_desc); Compatibility=$($value.compatibility_level); Collation=$($value.collation_name); Containment=$($value.containment_desc); Owner=$($value.OwnerName); DataFiles=$($value.DataFileCount); LogFiles=$($value.LogFileCount)" $(if($value.state_desc -eq 'ONLINE'){'PASS'}else{'FAIL'}) $(if($value.state_desc -eq 'ONLINE'){'INFO'}else{'HIGH'}) 'visible and ONLINE' 'Configured database metadata observed.' 'Restore availability through approved DBA change.' $true))}else{$results.Add((New-SqlCheck $prefix ('DATABASES.MISSING.{0:D3}' -f ([array]::IndexOf(@($SqlTarget.DatabasesToValidate),$database)+1)) DatabaseInventory 'Configured database' $targetName $database FAIL HIGH 'visible configured database' 'Database is missing or inaccessible.' 'Correct configuration or least-privilege access.' $true))}}}else{$results.Add((New-SqlCheck $prefix 'DATABASES.UNAVAILABLE' DatabaseInventory 'Database inventory' $targetName $databases.Error FAIL HIGH 'configured database metadata' 'Database inventory query failed.' 'Grant documented metadata access.' $true))}
                    $files=Invoke-SqlQuerySafe $Operations $connection $queries.DatabaseFiles @{'@DatabaseNames'=$databaseParameter} DatabaseFiles;$results.Add((New-SqlCheck $prefix 'FILES.INVENTORY' DatabaseFileCapacity 'Database files and capacity' $targetName $(if($files.Succeeded){"$($files.Rows.Count) configured file(s)"}else{$files.Error}) $(if($files.Succeeded){'PASS'}else{'WARNING'}) MEDIUM 'bounded configured database files'))
                    $backup=Invoke-SqlQuerySafe $Operations $connection $queries.BackupMetadata @{'@DatabaseNames'=$databaseParameter} BackupMetadata;$results.Add((New-SqlCheck $prefix 'BACKUP.OBSERVABILITY' BackupRecoveryObservability 'Backup metadata' $targetName $(if($backup.Succeeded){"$($backup.Rows.Count) configured database row(s)"}else{$backup.Error}) $(if($backup.Succeeded){'PASS'}else{'WARNING'}) LOW 'informational; no recency threshold'))
                    if($SqlTarget.ExpectedRole -eq 'OperationsDatabase'){$online=@($databases.Rows|Where-Object name -eq $Configuration.SqlServer.Database|Where-Object state_desc -eq ONLINE).Count -eq 1;$results.Add((New-SqlCheck $prefix 'OPERATIONS.ONLINE' OperationsDatabaseCompatibility 'Operations database online' $targetName $online $(if($online){'PASS'}else{'FAIL'}) $(if($online){'INFO'}else{'HIGH'}) $true 'Operations deployment state observed.' 'Complete approved database deployment.' $true));if($online){try{$schema=& $Operations.RunSchemaValidation $SqlTarget $Configuration;$results.Add((New-SqlCheck $prefix 'OPERATIONS.SCHEMA' OperationsDatabaseCompatibility 'Authoritative schema validation' $targetName $schema $(if($schema -eq 'PASS'){'PASS'}else{'FAIL'}) HIGH 'PASS' 'WP-009.3 validator result.' 'Use approved forward-fix process.' $true))}catch{$results.Add((New-OperationalExceptionResult "$prefix.OPERATIONS.SCHEMA" OperationsDatabaseCompatibility 'Authoritative schema validation' 'Run unchanged WP-009.3 read-only validator.' $targetName $_.Exception HIGH $true))};if(-not $SkipPermissionChecks){try{$permissionValidation=& $Operations.RunPermissionValidation $SqlTarget $Configuration;$results.Add((New-SqlCheck $prefix 'OPERATIONS.PERMISSIONPROFILE' OperationsDatabaseCompatibility 'Authoritative permission validation' $targetName $permissionValidation $(if($permissionValidation -eq 'PASS'){'PASS'}else{'FAIL'}) HIGH 'PASS' 'WP-009.4 validator result.' 'Apply only Security-approved least privilege through approved DBA change.' $true))}catch{$results.Add((New-OperationalExceptionResult "$prefix.OPERATIONS.PERMISSIONPROFILE" OperationsDatabaseCompatibility 'Authoritative permission validation' 'Run unchanged WP-009.4 read-only effective-permission validator.' $targetName $_.Exception HIGH $true))}}}}else{$results.Add((New-SqlCheck $prefix 'OPERATIONS.NOTAPPLICABLE' OperationsDatabaseCompatibility 'Operations database compatibility' $targetName $SqlTarget.ExpectedRole NOT_APPLICABLE INFO 'OperationsDatabase role'))}
                }
                if($SkipPermissionChecks){$results.Add((New-SqlCheck $prefix 'PERMISSIONS.SKIPPED' CollectorMetadataPermissions 'Permission checks skipped' $targetName $null SKIPPED MEDIUM 'operator-enabled permission checks' 'SkipPermissionChecks was supplied.' $null $true));$results.Add((New-SqlCheck $prefix 'PERFORMANCE.SKIPPED' PerformanceMetadataAvailability 'Permission-dependent probes skipped' $targetName $null SKIPPED MEDIUM 'permission validation' 'SkipPermissionChecks was supplied.' $null $true))}
                else{$permissions=Invoke-SqlQuerySafe $Operations $connection $queries.Permissions @{} Permissions;if($permissions.Succeeded -and $permissions.Rows.Count){$p=$permissions.Rows[0];foreach($item in @(@('CONNECTSQL','CONNECT SQL',$p.ConnectSql,$true),@('VIEWSERVERSTATE','VIEW SERVER STATE',$p.ViewServerState,$true),@('VIEWSERVERPERFORMANCE','VIEW SERVER PERFORMANCE STATE',$p.ViewServerPerformanceState,$false),@('VIEWANYDATABASE','VIEW ANY DATABASE',$p.ViewAnyDatabase,$false),@('CONNECTANYDATABASE','CONNECT ANY DATABASE',$p.ConnectAnyDatabase,$false))){$present=[int]$item[2] -eq 1;$mandatory=[bool]$item[3];$status=if($present){'PASS'}elseif($mandatory){'FAIL'}else{'WARNING'};$results.Add((New-SqlCheck $prefix "PERMISSIONS.$($item[0])" CollectorMetadataPermissions $item[1] $targetName $present $status $(if($status -eq 'FAIL'){'HIGH'}elseif($status -eq 'WARNING'){'LOW'}else{'INFO'}) $true 'Effective permission result.' 'Grant only the documented SQL Collector metadata permission.' $mandatory))};$sysadmin=[int]$p.IsSysadmin -eq 1;$results.Add((New-SqlCheck $prefix 'PERMISSIONS.SYSADMIN' SecurityPosture 'sysadmin membership' $targetName $sysadmin $(if($sysadmin){'WARNING'}else{'PASS'}) $(if($sysadmin){'HIGH'}else{'INFO'}) $false 'Broad privilege is not required.' 'Remove excessive privilege through approved DBA change.'))}else{$results.Add((New-SqlCheck $prefix 'PERMISSIONS.UNAVAILABLE' CollectorMetadataPermissions 'Permission metadata' $targetName $permissions.Error FAIL HIGH 'effective permission metadata' 'Permission query failed.' 'Grant only documented metadata visibility.' $true))}
                    $performance=Invoke-SqlQuerySafe $Operations $connection $queries.PerformanceMetadata @{} PerformanceMetadata;if($performance.Succeeded -and $performance.Rows.Count){$missing=@($performance.Rows[0].PSObject.Properties|Where-Object{$null -eq $_.Value}).Count;$results.Add((New-SqlCheck $prefix 'PERFORMANCE.SOURCES' PerformanceMetadataAvailability 'Required metadata sources' $targetName "$missing unavailable source(s)" $(if($missing){'FAIL'}else{'PASS'}) $(if($missing){'HIGH'}else{'INFO'}) 'all documented sources available' 'Bounded existence probe only.' 'Use supported version and required metadata permissions.' $true))}else{$results.Add((New-SqlCheck $prefix 'PERFORMANCE.UNAVAILABLE' PerformanceMetadataAvailability 'Required metadata sources' $targetName $performance.Error FAIL HIGH 'bounded metadata probe' 'Performance metadata probe failed.' 'Grant documented metadata visibility.' $true))}}
                $availability=Invoke-SqlQuerySafe $Operations $connection $queries.Availability @{} Availability;if($availability.Succeeded -and $availability.Rows.Count){$a=$availability.Rows[0];$results.Add((New-SqlCheck $prefix 'AVAILABILITY.OBSERVATION' AvailabilityFeatures 'Availability topology' $targetName "Clustered=$($a.IsClustered); HADR=$($a.IsHadrEnabled); AGs=$($a.AvailabilityGroupCount); Mirrored=$($a.MirroredDatabaseCount)" PASS INFO 'informational; no HA requirement'))}else{$results.Add((New-SqlCheck $prefix 'AVAILABILITY.UNAVAILABLE' AvailabilityFeatures 'Availability topology' $targetName $availability.Error WARNING LOW 'when permitted'))}
                $results.Add((New-SqlCheck $prefix 'SECURITY.CONFIGURATION' SecurityPosture 'Secret-free Windows authentication configuration' $targetName 'Integrated Security; Encrypt=True; TrustServerCertificate=False' PASS INFO 'approved repository policy' 'No credentials accepted or logged.' $null $true))
            }
        }
        $mandatory=@($results|Where-Object{$_.Mandatory -and $_.Category -ne 'SQLCollectorCompatibility'});$compat=if($mandatory|Where-Object Status -eq FAIL){'FAIL'}elseif($mandatory|Where-Object Status -in @('WARNING','SKIPPED')){'WARNING'}else{'PASS'};$results.Add((New-SqlCheck $prefix 'COMPATIBILITY.RESULT' SQLCollectorCompatibility 'SQL Collector compatibility' $targetName $compat $compat $(if($compat -eq 'FAIL'){'HIGH'}elseif($compat -eq 'WARNING'){'MEDIUM'}else{'INFO'}) 'all mandatory prerequisites pass' 'Advisory result; no Collector execution.' 'Resolve cited prerequisite findings.' $true));$results.Add((New-SqlCheck $prefix 'COMPATIBILITY.SOURCES' SQLCollectorCompatibility 'Compatibility source checks' $targetName (($mandatory|ForEach-Object CheckId)-join ',') PASS INFO 'constituent mandatory check identifiers'))
    } finally {if($null -ne $connection){& $Operations.CloseConnection $connection}}
    $results.ToArray()
}
