$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path;$historyRoot=Join-Path $repoRoot 'tools\validation\history'
. (Join-Path $repoRoot 'tools\validation\common\OperationalValidation.Common.ps1');. (Join-Path $repoRoot 'tools\validation\common\OperationalValidation.Reporting.ps1');. (Join-Path $repoRoot 'tools\validation\sql\SQLTarget.Queries.ps1');. (Join-Path $repoRoot 'tools\validation\sql\SQLTarget.Checks.ps1');. (Join-Path $historyRoot 'HistoryRetention.Queries.ps1');. (Join-Path $historyRoot 'HistoryRetention.Checks.ps1')
function New-Z8Facts{[pscustomobject]@{SchemaVersion=$true;Migration=$true;SixTables=$true;NoHistoryAudit=$true;NoJsonStore=$true;Projection=$true;Idempotency=$true;Partial=$true;Transitions=$true;Artifacts=$true;Provenance=$true;Queries=$true;Pagination=$true;Retention=$true;Cleanup=$true;NoScheduler=$true;NoDryRun=$true;FailureIsolation=$true;NoHistoryMetric=$true;HistoryAuditBoundary=$true}}
function New-Z8SqlResult{New-OperationalObservation SQL.REUSED SQLConnectivity SQL SQL operations-database PASS INFO $true $true mocked $null mocked $true}
function New-Z8Catalog{$tables=@('ExecutionRunHistory','ExecutionStepHistory','ExecutionAttemptHistory','ExecutionStateTransitionHistory','ExecutionArtifactHistory','ExecutionPolicyHistory')|ForEach-Object{[pscustomobject]@{SchemaName='history';TableName=$_}};$indexes=1..6|ForEach-Object{[pscustomobject]@{TableName=$tables[$_-1].TableName;IndexName="PK$_";is_unique=$true;is_primary_key=$true}};@{Migration=@([pscustomobject]@{MigrationId='20260729191745_WP0088ExecutionHistory'});Tables=$tables;Shape=@([pscustomobject]@{TableName='ExecutionRunHistory';ColumnName='ExecutionRunId';TypeName='uniqueidentifier';max_length=16;is_nullable=$false});Indexes=$indexes}}
function New-Z8Operations{param([bool]$Sql=$true,[object]$Facts=(New-Z8Facts),[object]$Catalog=(New-Z8Catalog));$result=${function:New-Z8SqlResult};@{GetSqlResults=({param($c,$t)if($Sql){@(& $result)}else{throw 'mock timeout'}}).GetNewClosure();GetCatalog=({param($c,$t)$Catalog}).GetNewClosure();GetFacts=({$Facts}).GetNewClosure()}}
Describe 'WP-007.Z.8 History and Retention validation' {
    BeforeEach{$configuration=Get-Content -Raw (Join-Path $repoRoot 'Release\Deployment\DeploymentConfiguration.sample.json')|ConvertFrom-Json;$target=@($configuration.SqlTargets|Where-Object ExpectedRole -eq OperationsDatabase)[0]}
    It 'accepts exact History configuration and Operations target selector' {(Test-HistoryRetentionConfiguration $configuration $target.Name).Name|Should Be $target.Name}
    It 'rejects missing and incorrect Operations target selectors' {{Test-HistoryRetentionConfiguration $configuration missing}|Should Throw;$configuration.SqlTargets[1].ValidationEnabled=$false;{Test-HistoryRetentionConfiguration $configuration}|Should Throw}
    It 'rejects invalid version profile batch dry-run and secret fields' {foreach($case in @('version','profile','batch','dryrun','secret')){$copy=Get-Content -Raw (Join-Path $repoRoot 'Release\Deployment\DeploymentConfiguration.sample.json')|ConvertFrom-Json;if($case -eq 'version'){$copy.HistoryValidation.ExpectedHistorySchemaVersion=2}elseif($case -eq 'profile'){$copy.HistoryValidation.RetentionPolicyProfile='Other'}elseif($case -eq 'batch'){$copy.HistoryValidation.RetentionBatchSize=501}elseif($case -eq 'dryrun'){$copy.HistoryValidation.RetentionDryRunEnabled=$true}else{$copy.HistoryValidation|Add-Member Password forbidden};{Test-HistoryRetentionConfiguration $copy}|Should Throw}}
    It 'contains only bounded read-only SQL catalog queries' {$queries=Get-HistoryRetentionQueries;{Assert-HistoryRetentionQueriesReadOnly $queries}|Should Not Throw;$queries.Count|Should Be 4}
    It 'implements all twenty-one categories with unique structured results' {$r=Invoke-HistoryRetentionChecks $configuration $target $repoRoot $false $false $false $false (New-Z8Operations);@($r.Category|Select-Object -Unique).Count|Should Be 21;{Assert-OperationalResults $r}|Should Not Throw}
    It 'reuses SQL success and validates schema migration tables and indexes' {$r=Invoke-HistoryRetentionChecks $configuration $target $repoRoot $false $false $false $false (New-Z8Operations);foreach($id in @('02.SQL','03.SCHEMA','04.TABLES','05.INDEXES')){($r|Where-Object CheckId -eq "H001.$id").Status|Should Be PASS}}
    It 'isolates SQL timeout and continues repository checks' {$r=Invoke-HistoryRetentionChecks $configuration $target $repoRoot $false $false $false $false (New-Z8Operations -Sql $false);($r|Where-Object CheckId -eq H001.02.SQL).Status|Should Be FAIL;($r|Where-Object CheckId -eq H001.06.PROJECTION).Status|Should Be PASS;($r|Where-Object CheckId -eq H001.03.SCHEMA).Status|Should Be SKIPPED}
    It 'detects missing schema version table and index evidence' {$facts=New-Z8Facts;$facts.SchemaVersion=$false;$catalog=New-Z8Catalog;$catalog.Tables=@($catalog.Tables|Select-Object -Skip 1);$catalog.Indexes=@();$r=Invoke-HistoryRetentionChecks $configuration $target $repoRoot $false $false $false $false (New-Z8Operations -Facts $facts -Catalog $catalog);foreach($id in @('03.SCHEMA','04.TABLES','05.INDEXES')){($r|Where-Object CheckId -eq "H001.$id").Status|Should Be FAIL}}
    It 'validates projection idempotency Partial transitions artifacts and provenance' {$r=Invoke-HistoryRetentionChecks $configuration $target $repoRoot $false $false $false $false (New-Z8Operations);foreach($id in @('06.PROJECTION','07.IDEMPOTENCY','08.PARTIAL','09.TRANSITIONS','10.ARTIFACTS','11.PROVENANCE')){($r|Where-Object CheckId -eq "H001.$id").Status|Should Be PASS}}
    It 'validates bounded queries paging retention and cleanup contracts' {$r=Invoke-HistoryRetentionChecks $configuration $target $repoRoot $false $false $false $false (New-Z8Operations);foreach($id in @('12.QUERY','13.PAGING','14.RETENTION','15.CLEANUP','17.PERFORMANCE')){($r|Where-Object CheckId -eq "H001.$id").Status|Should Be PASS}}
    It 'reports dry-run and History metrics not applicable without inventing them' {$r=Invoke-HistoryRetentionChecks $configuration $target $repoRoot $false $false $false $false (New-Z8Operations);($r|Where-Object CheckId -eq H001.16.DRYRUN).Status|Should Be NOT_APPLICABLE;($r|Where-Object CheckId -eq H001.19.MONITORING).Status|Should Be NOT_APPLICABLE}
    It 'preserves History versus Audit and failure isolation boundaries' {$r=Invoke-HistoryRetentionChecks $configuration $target $repoRoot $false $false $false $false (New-Z8Operations);($r|Where-Object CheckId -eq H001.18.ISOLATION).Status|Should Be PASS;($r|Where-Object CheckId -eq H001.20.BOUNDARY).Status|Should Be PASS}
    It 'honors every skip switch and makes readiness a warning' {$r=Invoke-HistoryRetentionChecks $configuration $target $repoRoot $true $true $true $true (New-Z8Operations);@($r|Where-Object Status -eq SKIPPED).Count|Should BeGreaterThan 10;($r|Where-Object CheckId -eq H001.21.READINESS).Status|Should Be WARNING}
    It 'produces FAIL readiness for repository contract defects' {$facts=New-Z8Facts;$facts.Pagination=$false;$r=Invoke-HistoryRetentionChecks $configuration $target $repoRoot $false $false $false $false (New-Z8Operations -Facts $facts);($r|Where-Object CheckId -eq H001.13.PAGING).Status|Should Be FAIL;($r|Where-Object CheckId -eq H001.21.READINESS).Status|Should Be FAIL}
    It 'uses deterministic common exit codes and rejects duplicate IDs' {Get-OperationalExitCode PASS|Should Be 0;Get-OperationalExitCode WARNING|Should Be 1;Get-OperationalExitCode FAIL|Should Be 2;$x=New-HistoryRetentionCheck X Category Name target $true;{Assert-OperationalResults @($x,$x)}|Should Throw}
    It 'sanitizes exceptions and writes fixed report files' {$e=New-OperationalExceptionResult H001.ERROR Failure Error expected target ([exception]'Password=forbidden; Server=private') HIGH $true;$e.ExceptionMessage|Should Not Match 'forbidden|private';$r=Invoke-HistoryRetentionChecks $configuration $target $repoRoot $false $false $false $false (New-Z8Operations);$report=New-OperationalReport $configuration ('a'*64) repository $target.Name ([datetime]::UtcNow) $r 'History and Retention Validation Report' HistoryRetentionValidation;$paths=Write-OperationalReports $report $TestDrive;Test-Path $paths.Json|Should Be $true;Test-Path $paths.Markdown|Should Be $true;Test-Path $paths.Log|Should Be $true}
    It 'contains no reachable retention execution mutation or authentication downgrade' {$content=(Get-Content -Raw (Join-Path $historyRoot 'HistoryRetention.Checks.ps1'))+(Get-Content -Raw (Join-Path $historyRoot 'Invoke-HistoryRetentionValidation.ps1'));$content|Should Not Match '(?i)DeleteExpiredAsync|Start-Service|Stop-Service|Restart-Service|Basic|NTLM|CredSSP|TrustedHosts|TrustServerCertificate\s*=\s*true'}
    It 'parses under Windows PowerShell 5.1' {foreach($path in Get-ChildItem $historyRoot -Filter *.ps1){$errors=$null;[void][Management.Automation.Language.Parser]::ParseFile($path.FullName,[ref]$null,[ref]$errors);$errors.Count|Should Be 0}}
}
