$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path;$portalRoot=Join-Path $repoRoot 'tools\validation\portal'
. (Join-Path $repoRoot 'tools\validation\common\OperationalValidation.Common.ps1');. (Join-Path $repoRoot 'tools\validation\common\OperationalValidation.Reporting.ps1');. (Join-Path $portalRoot 'PortalMonitoring.Checks.ps1')
function New-Z7Result{param($id,$category,$target,$status='PASS',[bool]$mandatory=$true)New-OperationalObservation $id $category $id $id $target $status $(if($status -eq 'FAIL'){'HIGH'}else{'INFO'}) $true $true 'mocked evidence' 'mocked recommendation' $id $mandatory}
function New-Z7Facts{param([bool]$Auth=$true,[bool]$Exporter=$false)[pscustomobject]@{GenericHealth=$true;DedicatedMonitoringEndpoint=$false;WindowsAuthentication=$Auth;AllowedHostsRestricted=$true;InstrumentationName=$true;InstrumentationVersion=$true;SchemaVersion=$true;SnapshotSchemaVersion=$true;MetricCatalog=$true;Meter=$true;Activities=$true;Snapshot=$true;HealthAssessment=$true;Subscriber=$true;LoggingSubscriber=$true;Composite=$true;HealthRegistration=$true;ExporterConfigured=$Exporter;BackendConfigured=$false}}
function New-Z7Operations{param([bool]$Auth=$true,[bool]$Tcp=$true,[int]$HttpStatus=200,[bool]$Database=$true,[bool]$Exporter=$false)
    $facts=New-Z7Facts $Auth $Exporter;$newResult=${function:New-Z7Result}
    @{ResolveDns=({param($n)@('192.0.2.1')}).GetNewClosure();TestTcp=({param($n,$p)$Tcp}).GetNewClosure();GetHttp=({param($u)[pscustomobject]@{StatusCode=$HttpStatus;ContentType='application/json';Location='';ElapsedMilliseconds=5}}).GetNewClosure();GetIis=({param($c,$p)@(& $newResult 'T001.COMPATIBILITY.RESULT' CollectorCompatibility $p.Server)}).GetNewClosure();GetDatabase=({param($c,$s)if($Database){@(& $newResult 'T001.COMPATIBILITY.RESULT' SQLCollectorCompatibility 'operations-database')}else{throw 'mock database unavailable'}}).GetNewClosure();GetRepositoryFacts=({$facts}).GetNewClosure();CurrentIdentity={'EXAMPLE\gmsa-portal$'}}
}
Describe 'WP-007.Z.7 Portal and Monitoring validation' {
    BeforeEach{$configuration=Get-Content -Raw (Join-Path $repoRoot 'Release\Deployment\DeploymentConfiguration.sample.json')|ConvertFrom-Json;$configuration.Portal.DeploymentExpected=$true}
    It 'accepts valid Portal and Monitoring configuration' {Test-PortalMonitoringConfiguration $configuration $configuration.Portal.Name|Should Be $true}
    It 'rejects a missing or wrong Portal selector' {{Test-PortalMonitoringConfiguration $configuration missing}|Should Throw}
    It 'rejects invalid scheme port and authentication' {foreach($change in @('scheme','port','auth')){$copy=Get-Content -Raw (Join-Path $repoRoot 'Release\Deployment\DeploymentConfiguration.sample.json')|ConvertFrom-Json;if($change -eq 'scheme'){$copy.Portal.Scheme='http'}elseif($change -eq 'port'){$copy.Portal.Port=0}else{$copy.Portal.AuthenticationMode='Basic'};{Test-PortalMonitoringConfiguration $copy $copy.Portal.Name}|Should Throw}}
    It 'rejects secret-bearing fields and invalid monitoring identity' {$configuration.Portal|Add-Member Token 'forbidden';{Test-PortalMonitoringConfiguration $configuration $configuration.Portal.Name}|Should Throw;$configuration.Portal.PSObject.Properties.Remove('Token');$configuration.MonitoringValidation.InstrumentationName='Vendor';{Test-PortalMonitoringConfiguration $configuration $configuration.Portal.Name}|Should Throw}
    It 'implements all eighteen categories with mocked operations' {$r=@(Invoke-PortalMonitoringChecks $configuration $repoRoot $false $false $false (New-Z7Operations));@($r.Category|Select-Object -Unique).Count|Should Be 18;{Assert-OperationalResults $r}|Should Not Throw}
    It 'records endpoint success and configured TCP only' {$r=Invoke-PortalMonitoringChecks $configuration $repoRoot $false $false $false (New-Z7Operations);($r|Where-Object CheckId -eq P001.HTTP.HEALTH).Status|Should Be PASS;($r|Where-Object CheckId -eq P001.NETWORK.TCP).Status|Should Be PASS}
    It 'records endpoint and database failures without stopping independent checks' {$r=Invoke-PortalMonitoringChecks $configuration $repoRoot $false $false $false (New-Z7Operations -HttpStatus 503 -Database $false);($r|Where-Object CheckId -eq P001.HTTP.HEALTH).Status|Should Be FAIL;($r|Where-Object CheckId -eq P001.DATABASE.ERROR).Status|Should Be FAIL;($r|Where-Object CheckId -eq P001.IDENTITY.CONTRACT).Status|Should Be PASS}
    It 'reports missing Windows Authentication as a bounded failure' {$r=Invoke-PortalMonitoringChecks $configuration $repoRoot $false $false $false (New-Z7Operations -Auth $false);($r|Where-Object CheckId -eq P001.AUTH.COMPOSITION).Status|Should Be FAIL}
    It 'reports absent deployment as not applicable without environment calls' {$configuration.Portal.DeploymentExpected=$false;$script:calls=0;$ops=New-Z7Operations;$ops.ResolveDns={$script:calls++};$r=Invoke-PortalMonitoringChecks $configuration $repoRoot $false $false $false $ops;$script:calls|Should Be 0;($r|Where-Object CheckId -eq P001.HTTP.STAGE).Status|Should Be NOT_APPLICABLE}
    It 'honors Portal Monitoring and database skip switches' {$r=Invoke-PortalMonitoringChecks $configuration $repoRoot $true $true $true (New-Z7Operations);@($r|Where-Object Status -eq SKIPPED).Count|Should BeGreaterThan 5}
    It 'distinguishes generic health from a nonexistent dedicated endpoint' {$r=Invoke-PortalMonitoringChecks $configuration $repoRoot $false $false $false (New-Z7Operations);($r|Where-Object CheckId -eq P001.HEALTH.PORTAL.GENERIC).Status|Should Be PASS;($r|Where-Object CheckId -eq P001.HEALTH.PORTAL.MONITORING).Status|Should Be NOT_APPLICABLE}
    It 'validates instrumentation metric Activity subscriber snapshot and health contracts' {$r=Invoke-PortalMonitoringChecks $configuration $repoRoot $false $false $false (New-Z7Operations);foreach($id in @('IDENTITY.CONTRACT','METRICS.CATALOG','ACTIVITIES.CONTRACT','SUBSCRIBER.COMPOSITION','SNAPSHOT.CONTRACT','HEALTH.CONTRACT','INTEGRATION.EVENTS')){($r|Where-Object CheckId -eq "P001.$id").Status|Should Be PASS}}
    It 'passes when no exporter is expected and fails when expected but absent' {$r=Invoke-PortalMonitoringChecks $configuration $repoRoot $false $false $false (New-Z7Operations);($r|Where-Object CheckId -eq P001.EXPORTER.EXPECTATION).Status|Should Be PASS;$configuration.MonitoringValidation.ExporterExpected=$true;$configuration.MonitoringValidation|Add-Member ExporterType OpenTelemetry;$configuration.MonitoringValidation|Add-Member ExporterEndpoint 'https://telemetry.example.invalid/v1';$r=Invoke-PortalMonitoringChecks $configuration $repoRoot $false $false $false (New-Z7Operations);($r|Where-Object CheckId -eq P001.EXPORTER.EXPECTATION).Status|Should Be FAIL}
    It 'produces PASS WARNING and FAIL readiness deterministically' {$pass=Invoke-PortalMonitoringChecks $configuration $repoRoot $false $false $false (New-Z7Operations);($pass|Where-Object CheckId -eq P001.READINESS.RESULT).Status|Should Be PASS;$configuration.Portal.DeploymentExpected=$false;$warning=Invoke-PortalMonitoringChecks $configuration $repoRoot $false $false $false (New-Z7Operations);($warning|Where-Object CheckId -eq P001.READINESS.RESULT).Status|Should Be PASS;$configuration.Portal.DeploymentExpected=$true;$fail=Invoke-PortalMonitoringChecks $configuration $repoRoot $false $false $false (New-Z7Operations -Auth $false);($fail|Where-Object CheckId -eq P001.READINESS.RESULT).Status|Should Be FAIL}
    It 'generates fixed JSON Markdown and log reports' {$r=Invoke-PortalMonitoringChecks $configuration $repoRoot $false $false $false (New-Z7Operations);$report=New-OperationalReport $configuration ('A'*64) source $configuration.Portal.Name ([datetime]::UtcNow) $r 'Portal and Monitoring Validation Report' 'PortalMonitoringValidation';$paths=Write-OperationalReports $report $TestDrive;Split-Path $paths.Json -Leaf|Should Be PortalMonitoringValidationReport.json;Split-Path $paths.Markdown -Leaf|Should Be PortalMonitoringValidationReport.md;Split-Path $paths.Log -Leaf|Should Be PortalMonitoringValidation.log}
    It 'uses deterministic common exit codes' {Get-OperationalExitCode PASS|Should Be 0;Get-OperationalExitCode WARNING|Should Be 1;Get-OperationalExitCode FAIL|Should Be 2}
    It 'rejects duplicate check identifiers' {$a=New-Z7Result SAME.ID Test target;{Assert-OperationalResults @($a,$a)}|Should Throw}
    It 'sanitizes exceptions' {(Protect-OperationalText 'Server=x;Password=secret;Token=abc')|Should Not Match 'secret|abc'}
    It 'defines the exact command and console contract' {$text=Get-Content -Raw (Join-Path $portalRoot 'Invoke-PortalMonitoringValidation.ps1');foreach($term in @('ConfigurationPath','OutputPath','PortalName','SkipPortalChecks','SkipMonitoringChecks','SkipDatabaseChecks','PORTAL AND MONITORING VALIDATION','exit 3','exit 4')){$text|Should Match ([regex]::Escape($term))}}
    It 'contains no prohibited mutation authentication or TLS bypass commands' {$prohibited=@('Start-Service','Stop-Service','Restart-Service','Set-Service','Restart-WebAppPool','Start-WebAppPool','Stop-WebAppPool','Set-WebConfigurationProperty','Set-ItemProperty','New-NetFirewallRule','Invoke-Collector');$hits=@();foreach($file in Get-ChildItem $portalRoot -Filter *.ps1){$tokens=$null;$errors=$null;$ast=[Management.Automation.Language.Parser]::ParseFile($file.FullName,[ref]$tokens,[ref]$errors);$errors.Count|Should Be 0;$hits+=@($ast.FindAll({param($n)$n -is [Management.Automation.Language.CommandAst] -and $n.GetCommandName() -in $prohibited},$true));(Get-Content -Raw $file.FullName)|Should Not Match '(?i)ServerCertificateValidationCallback|DangerousAcceptAny|Authentication\s*=\s*["'']?(Basic|NTLM|Negotiate|CredSSP)'};$hits.Count|Should Be 0}
}
