$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
$sqlRoot=Join-Path $repoRoot 'tools\validation\sql'
. (Join-Path $repoRoot 'tools\validation\common\OperationalValidation.Common.ps1')
. (Join-Path $repoRoot 'tools\validation\common\OperationalValidation.Reporting.ps1')
. (Join-Path $sqlRoot 'SQLTarget.Queries.ps1')
. (Join-Path $sqlRoot 'SQLTarget.Checks.ps1')

function New-TestSqlOperations {
    param([bool]$ConnectionSucceeds=$true,[string]$AuthScheme='KERBEROS',[string]$EncryptOption='TRUE',[bool]$MissingPermission=$false,[bool]$OperationsDatabase=$false)
    $queries=Get-SqlTargetValidationQueries
    $query=({param($connection,$text,$parameters)
        if($text -eq $queries.CoreMetadata){return @([pscustomobject]@{MachineName='SQL01';ServerName='SQL01';InstanceName='MSSQLSERVER';ProductVersion='16.0.1000.6';ProductLevel='RTM';Edition='Developer Edition';EngineEdition=3;IsClustered=$false;IsHadrEnabled=$false;LoginName='EXAMPLE\gmsa-sqlcollector$';auth_scheme=$AuthScheme;net_transport='TCP';encrypt_option=$EncryptOption;local_net_address='192.0.2.20';local_tcp_port=1433;client_net_address='192.0.2.10';SqlServerStartTime=[datetime]'2026-07-30'})}
        if($text -eq $queries.HostPlatform){return @([pscustomobject]@{host_platform='Windows';host_distribution='Windows Server';host_release='2022'})}
        if($text -eq $queries.ServerConfiguration){return @([pscustomobject]@{name='max server memory (MB)';ValueInUse=4096},[pscustomobject]@{name='max degree of parallelism';ValueInUse=0})}
        if($text -eq $queries.DatabaseInventory){$name=if($OperationsDatabase){'PSMOperationsPlatform'}else{'ExampleApplication'};return @([pscustomobject]@{name=$name;database_id=5;state_desc='ONLINE';user_access_desc='MULTI_USER';is_read_only=$false;recovery_model_desc='FULL';compatibility_level=160;collation_name='Latin1_General_100_CI_AS_SC';containment_desc='NONE';OwnerName='sa';create_date=[datetime]'2026-01-01';is_trustworthy_on=$false;is_db_chaining_on=$false;DataFileCount=1;LogFileCount=1})}
        if($text -eq $queries.DatabaseFiles){return @([pscustomobject]@{DatabaseName='ExampleApplication';type_desc='ROWS';LogicalName='Example';physical_name='D:\SQLData\Example.mdf';SizeBytes=1GB;max_size=-1;growth=65536;is_percent_growth=$false})}
        if($text -eq $queries.BackupMetadata){return @([pscustomobject]@{DatabaseName='ExampleApplication';LastFull=[datetime]'2026-07-30';LastDifferential=$null;LastLog=[datetime]'2026-07-31'})}
        if($text -eq $queries.Permissions){return @([pscustomobject]@{ConnectSql=1;ViewServerState=$(if($MissingPermission){0}else{1});ViewServerPerformanceState=1;ViewAnyDatabase=1;ConnectAnyDatabase=1;IsSysadmin=0})}
        if($text -eq $queries.PerformanceMetadata){return @([pscustomobject]@{Connections=1;Sessions=2;Requests=3;PerformanceCounters=4;SystemInfo=5;ProcessMemory=6;WaitStats=7;VirtualFileStats=8;Databases=9;MasterFiles=10})}
        if($text -eq $queries.Availability){return @([pscustomobject]@{IsClustered=$false;IsHadrEnabled=$false;AvailabilityGroupCount=0;MirroredDatabaseCount=0})}
        throw 'Unexpected query.'
    }).GetNewClosure()
    @{
        ResolveDns={param($name)@('192.0.2.20')};ResolveReverseDns={param($address)'managed-sql01.example.invalid'}
        TestTcp={param($name,$port)$true};GetRoute={param($address)[pscustomobject]@{InterfaceIndex=7;RouteMetric=10}}
        GetSpn={param($spn)@('Registered ServicePrincipalNames','MSSQLSvc/managed-sql01.example.invalid:1433')}
        OpenConnection=({param($target)if($ConnectionSucceeds){[pscustomobject]@{State='Open'}}else{throw 'connection timeout'}}).GetNewClosure()
        Query=$query;CloseConnection={param($connection)$script:SqlConnectionClosed=$true}
        RunSchemaValidation={param($target,$configuration)'PASS'};RunPermissionValidation={param($target,$configuration)'PASS'}
    }
}

Describe 'WP-007.Z.5 SQL target validation' {
    BeforeEach{$script:SqlConnectionClosed=$false;$configuration=Get-Content -Raw (Join-Path $repoRoot 'Release\Deployment\DeploymentConfiguration.sample.json')|ConvertFrom-Json;$managed=$configuration.SqlTargets|Where-Object ExpectedRole -eq ManagedSqlTarget;$operations=$configuration.SqlTargets|Where-Object ExpectedRole -eq OperationsDatabase}

    It 'loads valid explicit SQL targets from the shared configuration' {$loaded=Get-OperationalConfiguration (Join-Path $repoRoot 'Release\Deployment\DeploymentConfiguration.sample.json') $repoRoot;@($loaded.SqlTargets).Count|Should Be 2}
    It 'rejects an invalid unpopulated configuration before contact' {{Get-OperationalConfiguration (Join-Path $repoRoot 'Release\Deployment\DeploymentConfiguration.template.json') $repoRoot}|Should Throw}
    It 'implements all seventeen categories for a passing managed target' {$results=@(Invoke-SqlTargetChecks $configuration $managed 1 collector $false $false (New-TestSqlOperations));{Assert-OperationalResults $results}|Should Not Throw;foreach($category in @('TargetConfiguration','DNSNetworkConnectivity','SQLConnection','SQLServerIdentityVersion','SQLServiceProtocol','KerberosSPN','EncryptionTLS','ServerConfiguration','DatabaseInventory','OperationsDatabaseCompatibility','CollectorMetadataPermissions','PerformanceMetadataAvailability','DatabaseFileCapacity','BackupRecoveryObservability','AvailabilityFeatures','SecurityPosture','SQLCollectorCompatibility')){@($results|Where-Object Category -eq $category).Count -gt 0|Should Be $true};($results|Where-Object CheckId -eq 'T001.COMPATIBILITY.RESULT').Status|Should Be PASS;$script:SqlConnectionClosed|Should Be $true}
    It 'fails and skips dependent checks on connection timeout' {$results=@(Invoke-SqlTargetChecks $configuration $managed 1 collector $false $false (New-TestSqlOperations -ConnectionSucceeds $false));($results|Where-Object CheckId -eq 'T001.CONNECTION.OPEN').Status|Should Be FAIL;@($results|Where-Object Status -eq SKIPPED).Count -gt 5|Should Be $true;($results|Where-Object CheckId -eq 'T001.COMPATIBILITY.RESULT').Status|Should Be FAIL}
    It 'detects NTLM fallback' {$results=@(Invoke-SqlTargetChecks $configuration $managed 1 collector $false $false (New-TestSqlOperations -AuthScheme NTLM));($results|Where-Object CheckId -eq 'T001.KERBEROS.AUTHSCHEME').Status|Should Be FAIL}
    It 'detects encryption mismatch' {$results=@(Invoke-SqlTargetChecks $configuration $managed 1 collector $false $false (New-TestSqlOperations -EncryptOption FALSE));($results|Where-Object CheckId -eq 'T001.TLS.ENCRYPTED').Status|Should Be FAIL}
    It 'reports a missing required permission and compatibility failure' {$results=@(Invoke-SqlTargetChecks $configuration $managed 1 collector $false $false (New-TestSqlOperations -MissingPermission $true));($results|Where-Object CheckId -eq 'T001.PERMISSIONS.VIEWSERVERSTATE').Status|Should Be FAIL;($results|Where-Object CheckId -eq 'T001.COMPATIBILITY.RESULT').Status|Should Be FAIL}
    It 'marks optional operations validation not applicable for a managed target' {$results=@(Invoke-SqlTargetChecks $configuration $managed 1 collector $false $false (New-TestSqlOperations));($results|Where-Object CheckId -eq 'T001.OPERATIONS.NOTAPPLICABLE').Status|Should Be NOT_APPLICABLE}
    It 'runs the authoritative schema adapter for the Operations database' {$results=@(Invoke-SqlTargetChecks $configuration $operations 1 collector $false $false (New-TestSqlOperations -OperationsDatabase $true));($results|Where-Object CheckId -eq 'T001.OPERATIONS.SCHEMA').Status|Should Be PASS}
    It 'warns when mandatory database and permission checks are skipped' {$results=@(Invoke-SqlTargetChecks $configuration $managed 1 collector $true $true (New-TestSqlOperations));@($results|Where-Object Status -eq SKIPPED).Count|Should Be 7;($results|Where-Object CheckId -eq 'T001.COMPATIBILITY.RESULT').Status|Should Be WARNING}
    It 'uses target-prefixed unique identifiers for multi-target aggregation' {$one=@(Invoke-SqlTargetChecks $configuration $managed 1 collector $false $false (New-TestSqlOperations));$two=@(Invoke-SqlTargetChecks $configuration $managed 2 collector $false $false (New-TestSqlOperations));{Assert-OperationalResults @($one+$two)}|Should Not Throw;@($two|Where-Object CheckId -notmatch '^T002\.').Count|Should Be 0}
    It 'accepts every approved static query as read only' {foreach($query in (Get-SqlTargetValidationQueries).Values){Test-SqlTargetQuerySafety $query|Should Be $true}}
    It 'rejects every prohibited SQL operation' {foreach($verb in @('INSERT','UPDATE','DELETE','MERGE','CREATE','ALTER','DROP','TRUNCATE','GRANT','DENY','REVOKE','EXECUTE AS','RECONFIGURE','BACKUP','RESTORE','SHRINK','CHECKPOINT','DBCC FREEPROCCACHE','DBCC DROPCLEANBUFFERS','KILL')){Test-SqlTargetQuerySafety "SELECT 1; $verb sample"|Should Be $false}}
    It 'maps deterministic shared exit codes' {Get-OperationalExitCode PASS|Should Be 0;Get-OperationalExitCode WARNING|Should Be 1;Get-OperationalExitCode FAIL|Should Be 2;Get-OperationalExitCode INVALID_CONFIGURATION|Should Be 3;Get-OperationalExitCode EXECUTION_ERROR|Should Be 4}
    It 'writes fixed SQL report files through common reporting' {$results=@(Invoke-SqlTargetChecks $configuration $managed 1 collector $false $false (New-TestSqlOperations));$report=New-OperationalReport $configuration ('A'*64) collector managed ([datetime]'2026-07-31') $results 'SQL Target Validation Report' 'SQLTargetValidation';$paths=Write-OperationalReports $report $TestDrive;Split-Path $paths.Json -Leaf|Should Be SQLTargetValidationReport.json;Split-Path $paths.Markdown -Leaf|Should Be SQLTargetValidationReport.md;Split-Path $paths.Log -Leaf|Should Be SQLTargetValidation.log;(Get-Content -Raw $paths.Markdown)|Should Match '# SQL Target Validation Report'}
    It 'defines the exact command and final console contract' {$text=Get-Content -Raw (Join-Path $sqlRoot 'Invoke-SQLTargetValidation.ps1');foreach($term in @('ConfigurationPath','ComputerName','TargetName','OutputPath','SkipDatabaseChecks','SkipPermissionChecks','SQL TARGET VALIDATION:','exit 3','exit 4')){$text|Should Match ([regex]::Escape($term))}}
    It 'uses only current-identity Integrated Security and approved TLS policy' {$text=Get-Content -Raw (Join-Path $sqlRoot 'SQLTarget.Checks.ps1');$text.Contains("`$builder['Integrated Security']=`$true")|Should Be $true;$text.Contains("`$builder['Application Name']='PSM Operations SQL Target Validation'")|Should Be $true;$text.Contains("`$builder['ApplicationIntent']='ReadOnly'")|Should Be $true;$text|Should Not Match "(?i)User ID|Password=|PSCredential|AccessToken|ConnectRetryCount"}
    It 'contains no environment mutation commands' {$prohibited=@('Start-Service','Stop-Service','Restart-Service','Set-Service','Set-ItemProperty','New-NetFirewallRule','Set-ADServiceAccount','Setspn');$found=@();foreach($file in Get-ChildItem $sqlRoot -Filter *.ps1){$tokens=$null;$errors=$null;$ast=[Management.Automation.Language.Parser]::ParseFile($file.FullName,[ref]$tokens,[ref]$errors);$errors.Count|Should Be 0;$found+=@($ast.FindAll({param($node)$node -is [Management.Automation.Language.CommandAst] -and $node.GetCommandName() -in $prohibited},$true))};$found.Count|Should Be 0}
    It 'sanitizes exceptions and rejects duplicate identifiers' {$safe=New-OperationalExceptionResult TEST.SQL ERROR Error Description Target ([InvalidOperationException]::new('Password=marker'));$safe.ExceptionMessage|Should Be '[REDACTED]';{Assert-OperationalResults @($safe,$safe)}|Should Throw}
}
