$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path;$productionRoot=Join-Path $repoRoot 'tools\validation\production'
. (Join-Path $repoRoot 'tools\validation\common\OperationalValidation.Common.ps1');. (Join-Path $repoRoot 'tools\validation\common\OperationalValidation.Reporting.ps1');. (Join-Path $productionRoot 'ProductionReadiness.Evidence.ps1');. (Join-Path $productionRoot 'ProductionReadiness.Checks.ps1')
function New-Z10Facts{param([bool]$Portal=$false,[bool]$Backend=$false,[bool]$SecurityDefect=$false)[pscustomobject]@{RepositoryClean=$true;BaselineExists=$true;BaselineMatches=$true;CurrentCommit='a'*40;PortalWindowsAuthentication=$Portal;GenericHealth=$true;DedicatedMonitoringEndpoint=$false;ProductionExporter=$Backend;ProductionBackend=$Backend;ProductionScaleProven=$false;RetentionDryRun=$false;RetentionScheduler=$false;ArchitectureGovernance=$true;RepositoryQuality=$true;ReleaseArtifacts=$true;SecurityDefect=$SecurityDefect}}
function New-Z10Evidence{param([string]$Result='PASS')[pscustomobject]@{Present=$true;Valid=$true;Reason='EvidenceValid';Data=[pscustomobject]@{OverallResult=$Result;ProductionReadinessStatus=$(if($Result -eq 'PASS'){'READY_FOR_PRODUCTION'}else{'NOT_READY_FOR_PRODUCTION'})}}}
function New-Z10Operations{param([object]$Facts=(New-Z10Facts),[bool]$Evidence=$true,[bool]$Risk=$false,[bool]$Approvals=$true,[bool]$LiveConfig=$true,[string]$Rat='PASS');$ev=${function:New-Z10Evidence};@{GetRepositoryFacts=({param($b)$Facts}).GetNewClosure();ReadEvidence=({param($p)if(-not $Evidence){[pscustomobject]@{Present=$false;Valid=$false;Reason='EvidenceMissing';Data=$null}}elseif($p -like 'RAT/*'){& $ev $Rat}else{& $ev PASS}}).GetNewClosure();GetLiveConfigurationApproval=({$LiveConfig}).GetNewClosure();GetMonitoringRiskAcceptance=({$Risk}).GetNewClosure();GetRequiredApprovals=({$Approvals}).GetNewClosure()}}
function Invoke-Z10{param([object]$Configuration,[hashtable]$Operations,[bool]$Skip=$false)Invoke-ProductionReadinessChecks $Configuration $TestDrive '1.0.0' ('b'*40) ('c'*64) $Skip $Operations}
function New-DecisionGate{param($id,$status,[bool]$blocking=$false,[bool]$mandatory=$true)New-ProductionGate "TEST.$id" TestArea TestRequirement REPOSITORY $status HIGH $mandatory $blocking actual Owner risk remediation retest}
Describe 'WP-007.Z.10 Production Readiness validation' {
 BeforeEach{$configuration=Get-Content -Raw (Join-Path $repoRoot 'Release\Deployment\DeploymentConfiguration.sample.json')|ConvertFrom-Json}
    It 'produces NOT_READY when Portal Windows Authentication is missing' {$a=Invoke-Z10 $configuration (New-Z10Operations -Risk $true);$a.Decision|Should Be NOT_READY_FOR_PRODUCTION;($a.Gates|Where-Object GateId -eq PRD.11.PORTAL.AUTH).Actual|Should Be PortalAuthenticationNotComposed}
    It 'detects the complete Portal repository composition while retaining the Monitoring risk blocker' {$facts=Get-ProductionRepositoryFacts $repoRoot ('0'*40);$facts.PortalWindowsAuthentication|Should Be $true;$a=Invoke-Z10 $configuration (New-Z10Operations -Facts (New-Z10Facts -Portal $true) -Risk $false);$a.Decision|Should Be NOT_READY_FOR_PRODUCTION;($a.Gates|Where-Object GateId -eq PRD.12.MONITORING).Status|Should Be FAIL;($a.Gates|Where-Object GateId -eq PRD.19.RISKS).Actual|Should Not Match 'Portal authentication'}
 It 'produces insufficient evidence only after capability defects are resolved' {$a=Invoke-Z10 $configuration (New-Z10Operations -Facts (New-Z10Facts -Portal $true) -Evidence $false -Risk $true -Approvals $true -LiveConfig $false);$a.Decision|Should Be INSUFFICIENT_LIVE_EVIDENCE}
 It 'makes a blocking security defect NOT_READY' {(Invoke-Z10 $configuration (New-Z10Operations -Facts (New-Z10Facts -Portal $true -SecurityDefect $true) -Risk $true)).Decision|Should Be NOT_READY_FOR_PRODUCTION}
 It 'makes required but absent Monitoring backend NOT_READY' {$configuration.MonitoringValidation.ExporterExpected=$true;(Invoke-Z10 $configuration (New-Z10Operations -Facts (New-Z10Facts -Portal $true) -Risk $true)).Decision|Should Be NOT_READY_FOR_PRODUCTION}
 It 'requires risk acceptance when Monitoring backend is out of scope' {(Invoke-Z10 $configuration (New-Z10Operations -Facts (New-Z10Facts -Portal $true) -Risk $false)).Decision|Should Be NOT_READY_FOR_PRODUCTION}
 It 'permits ready with warnings for accepted no-backend posture when all else passes' {(Invoke-Z10 $configuration (New-Z10Operations -Facts (New-Z10Facts -Portal $true) -Risk $true)).Decision|Should Be READY_WITH_WARNINGS}
 It 'permits READY only with every mandatory capability evidence and approval' {$configuration.MonitoringValidation.ExporterExpected=$true;(Invoke-Z10 $configuration (New-Z10Operations -Facts (New-Z10Facts -Portal $true -Backend $true) -Risk $false)).Decision|Should Be READY_FOR_CONTROLLED_PRODUCTION_DEPLOYMENT}
 It 'never treats repository-only skipped live evidence as READY' {$configuration.MonitoringValidation.ExporterExpected=$true;(Invoke-Z10 $configuration (New-Z10Operations -Facts (New-Z10Facts -Portal $true -Backend $true)) $true).Decision|Should Be INSUFFICIENT_LIVE_EVIDENCE}
 It 'keeps production scale NOT PROVEN visible' {$a=Invoke-Z10 $configuration (New-Z10Operations -Risk $true);$a.Facts.ProductionScaleProven|Should Be $false;@($a.Gates|Where-Object GateId -eq PRD.15.PERFORMANCE).Count|Should Be 1}
 It 'blocks on missing and failed RAT according to precedence' {$missing=Invoke-Z10 $configuration (New-Z10Operations -Facts (New-Z10Facts -Portal $true) -Evidence $false -Risk $true);$missing.Decision|Should Be INSUFFICIENT_LIVE_EVIDENCE;$failed=Invoke-Z10 $configuration (New-Z10Operations -Facts (New-Z10Facts -Portal $true) -Risk $true -Rat FAIL);$failed.Decision|Should Be NOT_READY_FOR_PRODUCTION}
 It 'blocks mismatched evidence' {$ops=New-Z10Operations -Facts (New-Z10Facts -Portal $true) -Risk $true;$ops.ReadEvidence={[pscustomobject]@{Present=$true;Valid=$false;Reason='EvidenceAlignmentMismatch';Data=$null}};(Invoke-Z10 $configuration $ops).Decision|Should Be NOT_READY_FOR_PRODUCTION}
 It 'makes missing mandatory human approval NOT_READY' {(Invoke-Z10 $configuration (New-Z10Operations -Facts (New-Z10Facts -Portal $true) -Risk $true -Approvals $false)).Decision|Should Be NOT_READY_FOR_PRODUCTION}
 It 'maps accepted nonblocking warning only after mandatory gates pass' {$g=@((New-DecisionGate A PASS),(New-DecisionGate B WARNING $false $false));(Get-ProductionReadinessDecision $g)|Should Be READY_WITH_WARNINGS}
 It 'enforces decision precedence directly' {(Get-ProductionReadinessDecision @((New-DecisionGate A FAIL $true),(New-DecisionGate B MISSING)))|Should Be NOT_READY_FOR_PRODUCTION;(Get-ProductionReadinessDecision @((New-DecisionGate A PASS),(New-DecisionGate B MISSING)))|Should Be INSUFFICIENT_LIVE_EVIDENCE}
 It 'maps deterministic exit codes' {Get-ProductionDecisionExitCode READY_FOR_CONTROLLED_PRODUCTION_DEPLOYMENT|Should Be 0;Get-ProductionDecisionExitCode READY_WITH_WARNINGS|Should Be 1;Get-ProductionDecisionExitCode NOT_READY_FOR_PRODUCTION|Should Be 2;Get-ProductionDecisionExitCode INSUFFICIENT_LIVE_EVIDENCE|Should Be 2}
 It 'rejects duplicate Gate IDs and malformed risk-capable gates' {$g=New-DecisionGate X PASS;{Assert-ProductionGates @($g,$g)}|Should Throw}
 It 'validates evidence alignment and missing evidence without live contact' {$missing=Read-ProductionEvidence $TestDrive missing.json 1.0.0 ('a'*40) ('b'*64);$missing.Present|Should Be $false;$data=@{ReleaseVersion='1.0.0';GitCommit='a'*40;ConfigurationHash='b'*64;Timestamp=[datetime]::UtcNow.ToString('o');OverallResult='PASS'}|ConvertTo-Json;$path=Join-Path $TestDrive valid.json;Set-Content $path $data;(Read-ProductionEvidence $TestDrive valid.json 1.0.0 ('a'*40) ('b'*64)).Valid|Should Be $true}
 It 'generates deterministic common JSON Markdown and log reports' {$a=Invoke-Z10 $configuration (New-Z10Operations -Risk $true);$report=New-OperationalReport $configuration ('c'*64) repository release ([datetime]::UtcNow) $a.Gates 'Production Readiness Report' ProductionReadiness;$report|Add-Member FinalDecision $a.Decision;$paths=Write-OperationalReports $report $TestDrive;Test-Path $paths.Json|Should Be $true;Test-Path $paths.Markdown|Should Be $true;Test-Path $paths.Log|Should Be $true}
 It 'defines all twenty categories with unique structured gates' {$a=Invoke-Z10 $configuration (New-Z10Operations -Risk $true);@($a.Gates.Category|Select-Object -Unique).Count|Should Be 20;{Assert-ProductionGates $a.Gates}|Should Not Throw}
 It 'contains no live connection mutation authentication downgrade or unsafe SQL' {$content=(Get-Content -Raw (Join-Path $productionRoot 'ProductionReadiness.Checks.ps1'))+(Get-Content -Raw (Join-Path $productionRoot 'Invoke-ProductionReadinessValidation.ps1'));$content|Should Not Match '(?i)SqlConnection|Invoke-Command|HttpWebRequest|Start-Service|Stop-Service|Restart-Service|Basic|NTLM|CredSSP|TrustedHosts|\b(INSERT|UPDATE|DELETE|MERGE|CREATE|ALTER|DROP|GRANT|DENY|REVOKE)\b'}
 It 'parses under Windows PowerShell 5.1' {foreach($path in Get-ChildItem $productionRoot -Filter *.ps1){$errors=$null;[void][Management.Automation.Language.Parser]::ParseFile($path.FullName,[ref]$null,[ref]$errors);$errors.Count|Should Be 0}}
}
