$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path;$performanceRoot=Join-Path $repoRoot 'tools\validation\performance'
. (Join-Path $repoRoot 'tools\validation\common\OperationalValidation.Common.ps1');. (Join-Path $repoRoot 'tools\validation\common\OperationalValidation.Reporting.ps1');. (Join-Path $performanceRoot 'PerformanceScale.Profiles.ps1');. (Join-Path $performanceRoot 'PerformanceScale.Checks.ps1')
function New-Z9Facts{[pscustomobject]@{Runtime=$true;Dispatcher=$true;Cancellation=$true;Semaphore=$true;TimeProvider=$true;Monitoring=$true;Cardinality=$true;Snapshot=$true;History=$true;Partial=$true;NoTracking=$true;Pagination=$true;Retention=$true;Inventory=$true;Release=$true;MonitoringGuard=$true;NoBenchmarkDotNet=$true}}
Describe 'WP-007.Z.9 Performance and Scale validation' {
    BeforeEach{$configuration=Get-Content -Raw (Join-Path $repoRoot 'Release\Deployment\DeploymentConfiguration.sample.json')|ConvertFrom-Json;$facts=New-Z9Facts;$provider=({$facts}).GetNewClosure()}
    It 'defines exact bounded Smoke Standard and Extended profiles' {
        $smoke=Get-PerformanceValidationProfile Smoke;$standard=Get-PerformanceValidationProfile Standard;$extended=Get-PerformanceValidationProfile Extended
        @($smoke.SyntheticTargetCount,$smoke.SyntheticRunCount,$smoke.SyntheticStepCount,$smoke.MaximumParallelism,$smoke.WarmupIterations,$smoke.MeasurementIterations)-join ','|Should Be '5,10,5,1,1,3'
        @($standard.SyntheticTargetCount,$standard.SyntheticRunCount,$standard.SyntheticStepCount,$standard.MaximumParallelism,$standard.WarmupIterations,$standard.MeasurementIterations)-join ','|Should Be '20,100,10,2,2,5'
        @($extended.SyntheticTargetCount,$extended.SyntheticRunCount,$extended.SyntheticStepCount,$extended.MaximumParallelism,$extended.WarmupIterations,$extended.MeasurementIterations)-join ','|Should Be '100,1000,20,4,3,7'
    }
    It 'accepts valid configuration and safely overrides with a code-owned profile' {(Test-PerformanceValidationConfiguration $configuration).Name|Should Be Smoke;(Test-PerformanceValidationConfiguration $configuration Standard).SyntheticRunCount|Should Be 100}
    It 'rejects mismatches unsafe live settings and secret fields' {
        $configuration.PerformanceValidation.SyntheticRunCount=11;{Test-PerformanceValidationConfiguration $configuration}|Should Throw
        $configuration.PerformanceValidation.SyntheticRunCount=10;$configuration.PerformanceValidation.LivePerformanceValidationEnabled=$true;{Test-PerformanceValidationConfiguration $configuration}|Should Throw
        $configuration.PerformanceValidation.LivePerformanceValidationEnabled=$false;$configuration.PerformanceValidation|Add-Member Token forbidden;{Test-PerformanceValidationConfiguration $configuration}|Should Throw
    }
    It 'creates a deterministic matrix with no production claim' {$a=New-PerformanceScaleMatrix (Get-PerformanceValidationProfile Smoke);$b=New-PerformanceScaleMatrix (Get-PerformanceValidationProfile Smoke);($a|ConvertTo-Json -Depth 4)|Should Be ($b|ConvertTo-Json -Depth 4);@($a|Where-Object Claim -ne 'NO PRODUCTION CLAIM').Count|Should Be 0}
    It 'implements all twenty-one categories with valid unique results' {$run=Invoke-PerformanceScaleChecks $configuration (Get-PerformanceValidationProfile Smoke) $repoRoot $false $false $false $false $false $false $provider;@($run.Results.Category|Select-Object -Unique).Count|Should Be 21;{Assert-OperationalResults $run.Results}|Should Not Throw}
    It 'preserves frozen Runtime Monitoring History and retention authorities' {$run=Invoke-PerformanceScaleChecks $configuration (Get-PerformanceValidationProfile Smoke) $repoRoot $false $false $false $false $false $false $provider;($run.Results|Where-Object CheckId -eq PERF.04.CONCURRENCY).Status|Should Be PASS;($run.Results|Where-Object CheckId -eq PERF.06.MONITORING).Message|Should Match '10,000/15-second';($run.Results|Where-Object CheckId -eq PERF.10.RETENTION).Message|Should Match 'no query plan or deletion'}
    It 'continues independent checks after a correctness failure' {$facts.Runtime=$false;$run=Invoke-PerformanceScaleChecks $configuration (Get-PerformanceValidationProfile Smoke) $repoRoot $false $false $false $false $false $false $provider;($run.Results|Where-Object CheckId -eq PERF.02.RUNTIME).Status|Should Be FAIL;($run.Results|Where-Object CheckId -eq PERF.13.RELEASE).Status|Should Be PASS;($run.Results|Where-Object CheckId -eq PERF.21.READINESS).Status|Should Be FAIL}
    It 'honors every skip family with structured skips' {$run=Invoke-PerformanceScaleChecks $configuration (Get-PerformanceValidationProfile Smoke) $repoRoot $true $true $true $true $true $false $provider;@($run.Results|Where-Object Status -eq SKIPPED).Count|Should BeGreaterThan 10}
    It 'keeps machine-sensitive benchmarks optional and advisory' {$off=Invoke-PerformanceScaleChecks $configuration (Get-PerformanceValidationProfile Smoke) $repoRoot $false $false $false $false $false $false $provider;$on=Invoke-PerformanceScaleChecks $configuration (Get-PerformanceValidationProfile Smoke) $repoRoot $false $false $false $false $false $true $provider;($off.Results|Where-Object CheckId -eq PERF.20.BUDGETS).Status|Should Be NOT_APPLICABLE;($on.Results|Where-Object CheckId -eq PERF.20.BUDGETS).Status|Should Be WARNING}
    It 'maps PASS WARNING and FAIL to deterministic exit codes' {Get-OperationalExitCode PASS|Should Be 0;Get-OperationalExitCode WARNING|Should Be 1;Get-OperationalExitCode FAIL|Should Be 2}
    It 'rejects duplicate check identifiers' {$r=New-PerformanceScaleCheck X Category Name $true;{Assert-OperationalResults @($r,$r)}|Should Throw}
    It 'sanitizes exception evidence' {$r=New-OperationalExceptionResult PERF.ERROR FailurePathPerformance Error expected repository-local ([exception]'Password=forbidden; server=private') HIGH $true;$r.ExceptionMessage|Should Not Match 'forbidden|private'}
    It 'generates fixed JSON Markdown and log reports' {$run=Invoke-PerformanceScaleChecks $configuration (Get-PerformanceValidationProfile Smoke) $repoRoot $false $false $false $false $false $false $provider;$report=New-OperationalReport $configuration ('a'*64) repository Smoke ([datetime]::UtcNow) $run.Results 'Performance and Scale Validation Report' PerformanceScaleValidation;$paths=Write-OperationalReports $report $TestDrive;Test-Path $paths.Json|Should Be $true;Test-Path $paths.Markdown|Should Be $true;Test-Path $paths.Log|Should Be $true}
    It 'contains no live transport or mutation implementation' {$content=(Get-Content -Raw (Join-Path $performanceRoot 'PerformanceScale.Checks.ps1'))+(Get-Content -Raw (Join-Path $performanceRoot 'Invoke-PerformanceScaleValidation.ps1'));$content|Should Not Match '(?i)Invoke-Command|SqlConnection|HttpWebRequest|Start-Service|Stop-Service|Restart-Service|Remove-Item|\b(INSERT|UPDATE|DELETE|MERGE|CREATE|ALTER|DROP|TRUNCATE|GRANT|DENY|REVOKE)\b'}
    It 'contains no authentication downgrade or high-cardinality metric dimensions' {$content=Get-Content -Raw (Join-Path $performanceRoot 'PerformanceScale.Checks.ps1');$content|Should Not Match '(?i)Basic|NTLM|TrustedHosts|CredSSP|ExecutionRunId.*dimension|ManagedServerId.*dimension|exception.message.*dimension'}
    It 'parses under Windows PowerShell 5.1' {foreach($path in Get-ChildItem $performanceRoot -Filter *.ps1){$errors=$null;[void][Management.Automation.Language.Parser]::ParseFile($path.FullName,[ref]$null,[ref]$errors);$errors.Count|Should Be 0}}
}
