<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PSMOperationsPlatform.CollectorSdk\PSMOperationsPlatform.CollectorSdk.csproj" />
    <ProjectReference Include="..\PSMOperationsPlatform.Contracts\PSMOperationsPlatform.Contracts.csproj" />
    <ProjectReference Include="..\PSMOperationsPlatform.Domain\PSMOperationsPlatform.Domain.csproj" />
  </ItemGroup>
</Project>
